### ISSUE TITLE
ProjectPasskeys: NPE none attestation from app

### ISSUE THREAD

**Issue by maduvena** [JanssenProject/jans#10113]
**Describe the bug**
```
REQUEST: https://imran-ishaq-obliging-gazelle.gluu.info/jans-fido2/restv1/attestation/options
METHOD: HttpMethod(value=POST)
COMMON HEADERS
-> Accept: application/json
-> Accept-Charset: UTF-8
CONTENT HEADERS
-> Content-Length: 65
-> Content-Type: application/json
BODY Content-Type: application/json
BODY START
{"username":"nazar1","displayName":"nazar1","attestation":"none"}
BODY END
RESPONSE: 500 Server Error
METHOD: HttpMethod(value=POST)
FROM: https://imran-ishaq-obliging-gazelle.gluu.info/jans-fido2/restv1/attestation/options
COMMON HEADERS
-> connection: close
-> content-length: 87
-> content-type: application/json
-> date: Mon, 11 Nov 2024 14:49:22 GMT
-> server: Apache/2.4.52 (Ubuntu)
-> strict-transport-security: max-age=31536000; includeSubDomains
-> x-content-type-options: nosniff
-> x-xss-protection: 1; mode=block
BODY Content-Type: application/json
BODY START
{
"error_description": "Unknown or not found error",
"error": "unknown_error"
}
BODY END

```

**Logs**

```
11-11 14:49:22.768 DEBUG [qtp1071097621-20] [jans.as.common.service.common.UserService] (UserService.java:78) - Getting user information from LDAP: userId = nazar1                                                                                                                                                     11-11 14:49:22.770 DEBUG [qtp1071097621-20] [jans.as.common.service.common.UserService] (UserService.java:93) - Found 1 entries for user id = nazar1        11-11 14:49:22.772 DEBUG [qtp1071097621-20] [io.jans.fido2.service.operation.AttestationService] (AttestationService.java:183) - Put authenticatorSelection AuthenticatorSelection{authenticatorAttachment=CROSS_PLATFORM, userVerification=required, requireResidentKey=false, residentKey=null}                       11-11 14:49:22.772 ERROR [qtp1071097621-20] [jans.fido2.ws.rs.controller.AttestationController] (AttestationController.java:96) - Unknown Error: Cannot invoke "String.equals(Object)" because the return value of "io.jans.fido2.model.conf.Fido2Configuration.getAttestationMode()" is null                           java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "io.jans.fido2.model.conf.Fido2Configuration.getAttestationMode()" is null                                                                                                                                                    at io.jans.fido2.service.operation.AttestationService.options(AttestationService.java:195) ~[classes/:?]                                                    at io.jans.fido2.service.operation.AttestationService$Proxy$_$$_WeldClientProxy.options(Unknown Source) ~[classes/:?]                                       at io.jans.fido2.ws.rs.controller.AttestationController.lambda$register$0(AttestationController.java:67) ~[classes/:?]                                      at io.jans.fido2.ws.rs.controller.AttestationController.processRequest(AttestationController.java:92) ~[classes/:?]                                         at io.jans.fido2.ws.rs.controller.AttestationController.register(AttestationController.java:63) ~[classes/:?]
        at io.jans.fido2.ws.rs.controller.AttestationController$Proxy$_$$_WeldClientProxy.register(Unknown Source) ~[classes/:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:569) ~[?:?]
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170) ~[resteasy-core-6.0.3.Final.jar:6.0.3.Final]
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130) ~[resteasy-core-6.0.3.Final.jar:6.0.3.Final]
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660) ~[resteasy-core-6.0.3.Final.jar:6.0.3.Final]        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524) ~[resteasy-core-6.0.3.Final.jar:6.0.3
```

**Comment by maduvena** [comment]
Not reproducible
