### ISSUE TITLE
fix(jans-scim): startup issues

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#1459]
Service not starting, seeing this in logs

```
org.jboss.weld.exceptions.DeploymentException: WELD-001409: Ambiguous dependencies for type SmtpConfiguration with qualifiers @Default|  at injection point [BackedAnnotatedField] @Inject private io.jans.service.MailService.smtpConfiguration|  at io.jans.service.MailService.smtpConfiguration(MailService.java:0)|  Possible dependencies: |  - Producer Method [SmtpConfiguration] with qualifiers [@Any @Default] declared as [[BackedAnnotatedMethod] @Produces @RequestScoped public io.jans.scim.service.ApplicationFactory.getSmtpConfiguration()],|  - Producer Method [SmtpConfiguration] with qualifiers [@Any @Default] declared as [[BackedAnnotatedMethod] @Produces @RequestScoped public io.jans.as.common.service.common.ApplicationFactory.getSmtpConfiguration()]|
	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:386)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:290)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:143)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:164)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:526)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:64)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by jgomer2001** [comment]
These problem was introduced with the addition of `jans-auth-common` dependency as part of solution of issue #1145 . This brought a series of CDI dependency problems. It's better to have a `ExternalIdGeneratorService` class inside `jans-scim` project instead of reusing the `jans-auth-common` one.
