### ISSUE TITLE
bug(jans-orm): UnsupportedOperationException thrown when using hybrid persistence

### ISSUE THREAD

**Issue by iromli** [JanssenProject/jans#1513]
**Describe the bug**

An error of `java.lang.UnsupportedOperationException: Entry class is manadatory for remove operation!` is thrown when user tries to login via Casa UI.

```
java.lang.UnsupportedOperationException: Entry class is manadatory for remove operation!                                             
        at io.jans.orm.sql.impl.SqlEntryManager.removeByDn(SqlEntryManager.java:282) ~[jans-orm-sql-1.0.1-SNAPSHOT.jar:?]            
        at io.jans.orm.impl.BaseEntryManager.remove(BaseEntryManager.java:454) ~[jans-orm-core-1.0.1-SNAPSHOT.jar:?]                 
        at io.jans.orm.hybrid.impl.HybridEntryManager.removeByDn(HybridEntryManager.java:386) ~[jans-orm-hybrid-1.0.1-SNAPSHOT.jar:?]
        at io.jans.orm.impl.BaseEntryManager.remove(BaseEntryManager.java:467) ~[jans-orm-core-1.0.1-SNAPSHOT.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]    
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]    
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
        at io.jans.orm.PersistenceEntryManager$EntityManager$2057902728$Proxy$_$$_WeldClientProxy.remove(Unknown Source) ~[jans-orm-core-1.0.1-SNAPSHO
T.jar:?]
        at io.jans.as.server.service.SessionIdService.remove(SessionIdService.java:850) ~[classes/:?]
        at io.jans.as.server.service.SessionIdService.setSessionIdStateAuthenticated(SessionIdService.java:545) ~[classes/:?]
        at io.jans.as.server.service.SessionIdService$Proxy$_$$_WeldClientProxy.setSessionIdStateAuthenticated(Unknown Source) ~[classes/:?]
        at io.jans.as.server.service.AuthenticationService.configureSessionUser(AuthenticationService.java:603) ~[classes/:?]
```

**To Reproduce**
1. Deploy Janssen Server 1.0.1-SNAPSHOT with hybrid persistence (`sql` + `spanner`) where `user` mapping is set to `spanner` and the rest of mapping set to `sql`
2. Deploy Casa 5.0.0-SNAPSHOT
3. Login to Casa UI (fill in appropriate credentials) and click submit
4. See error log of auth-server

**Expected behavior**

No error thrown by jans-auth ~and user able to log in~.

**Additional context**

Logs attached
[auth-server.log.md](https://github.com/JanssenProject/jans/files/8847806/auth-server.log.md)

**Comment by iromli** [comment]
Update: after few retries, user able to login via Casa UI. The errors persist though regardless user able to log in or not.

**Comment by ossdhaval** [comment]
Hi @iromli, since this issue has been open for a long time, can you check if this is still relevant and needs to be fixed?

**Comment by iromli** [comment]
@ossdhaval sure, i will check it as soon as possible

**Comment by iromli** [comment]
The issue is resolved.
