### ISSUE TITLE
error while installing jans server on SUSE/RHEL8

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1537]
**Describe the bug**
getting below error while installing jans server on RHEL8

[root@localhost admin]# sudo python3 /opt/jans/jans-setup/setup.py
**Traceback (most recent call last):
  File "/opt/jans/jans-setup/setup.py", line 109, in <module>
    from setup_app.test_data_loader import TestDataLoader
  File "/opt/jans/jans-setup/setup_app/test_data_loader.py", line 16, in <module>
    from setup_app.installers.base import BaseInstaller
  File "/opt/jans/jans-setup/setup_app/installers/base.py", line 10, in <module>
    from setup_app.utils.db_utils import dbUtils
  File "/opt/jans/jans-setup/setup_app/utils/db_utils.py", line 25, in <module>
    from setup_app.utils.spanner import Spanner
  File "/opt/jans/jans-setup/setup_app/utils/spanner.py", line 6, in <module>
    from google.cloud import spanner
  File "/opt/jans/jans-setup/setup_app/pylib/gcs/google/cloud/spanner.py", line 17, in <module>
    from google.cloud.spanner_v1 import __version__
  File "/opt/jans/jans-setup/setup_app/pylib/gcs/google/cloud/spanner_v1/__init__.py", line 23, in <module>
    from .services.spanner import SpannerClient
  File "/opt/jans/jans-setup/setup_app/pylib/gcs/google/cloud/spanner_v1/services/spanner/__init__.py", line 18, in <module>
    from .client import SpannerClient
  File "/opt/jans/jans-setup/setup_app/pylib/gcs/google/cloud/spanner_v1/services/spanner/client.py", line 27, in <module>
    from google.api_core import gapic_v1  # type: ignore
  File "/opt/jans/jans-setup/setup_app/pylib/gcs/google/api_core/gapic_v1/__init__.py", line 18, in <module>
    from google.api_core.gapic_v1 import config
  File "/opt/jans/jans-setup/setup_app/pylib/gcs/google/api_core/gapic_v1/config.py", line 23, in <module>
    import grpc
  File "/opt/jans/jans-setup/setup_app/pylib/gcs/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/opt/jans/jans-setup/setup_app/pylib/gcs/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
ImportError: cannot import name 'cygrpc'**

**To Reproduce**
run below commands 
yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
yum module enable mod_auth_openidc
yum install curl
yum install -y https:$(curl -s -L https://api.github.com/repos/JanssenProject/jans/releases/latest | egrep -o '/.*el8.x86_64.rpm' | head -n 1)
sudo python3 /opt/jans/jans-setup/setup.py

**Expected behavior**
installation should complete without any error

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/173019796-c45eea57-c7f4-4d1f-8781-b2b0161b6bb9.png)

**Desktop (please complete the following information):**
  - OS: RHEL8
  - Browser 
  - Version 

**Smartphone (please complete the following information):**

**Additional context**
installing jans on RHEL8 VMware instance

**Comment by devrimyatar** [comment]
The issue for bot SUSE and RHEL8 (CentOS8-AS) is that, they are packaged with python3.8 rather than python3.6.
@nikdavnik please update your packaging script so that it uses python3.6 when executing `install.py --download-exit`
