### ISSUE TITLE
fix (jans-config-api) : fido2-plugin throwing error during deployment

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#1632]
**Describe the bug**
The fido2-plugin throwing following error during deployment if user-mgt-plugin is not deployed.

```
2022-06-28 20:43:44.053:WARN :oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@5c87bfe2{jans-config-api.xml,/jans-config-api,[file:///tmp/jetty-0_0_0_0-8074-jans-config-api_war-_jans-config-api-any-16968549411140458976/webapp/, jar:file:///tmp/jetty-0_0_0_0-8074-jans-config-api_war-_jans-config-api-any-16968549411140458976/webapp/WEB-INF/lib/jakarta.faces-3.0.2.jar!/META-INF/resources],UNAVAILABLE}{/opt/jans/jetty/jans-config-api/webapps/jans-config-api.war}
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type UserService with qualifiers @Default|  at injection point [BackedAnnotatedField] @Inject private io.jans.configapi.plugin.fido2.service.Fido2RegistrationService.userService|  at io.jans.configapi.plugin.fido2.service.Fido2RegistrationService.userService(Fido2RegistrationService.java:0)|
        at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:378)
        at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:290)
        at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:143)
        at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:164)
        at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:526)
        at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:64)
        at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:62)
        at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
        at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
2022-06-28 20:43:44.071:INFO :oejs.AbstractConnector:main: Started ServerConnector@53f0a4cb{HTTP/1.1, (http/1.1)}{0.0.0.0:8074}
2022-06-28 20:43:44.073:INFO :oejs.Server:main: Started Server@17a1e4ca{STARTING}[11.0.8,sto=5000] @14357ms
```

**Comment by duttarnab** [comment]
Done
