### ISSUE TITLE
bug(jans-auth-server): npe in JwtAuthorizationRequest 

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#1641]
**Describe the bug**

NPE in JwtAuthorizationRequest (reproducible with ciba)
```
Caused by: java.lang.NullPointerException
        at io.jans.as.server.model.authorize.JwtAuthorizationRequest.createJwtRequest(JwtAuthorizationRequest.java:516) ~[classes/:?]
        at io.jans.as.server.bcauthorize.ws.rs.BackchannelAuthorizeRestWebServiceImpl.requestBackchannelAuthorizationPost(BackchannelAuthorizeRestWebServiceImpl.java:172) ~[classes/:?]
        at io.jans.as.server.bcauthorize.ws.rs.BackchannelAuthorizeRestWebServiceImpl$Proxy$_$$_WeldClientProxy.requestBackchannelAuthorizationPost(Unknown Source) ~[classes/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]

```

**Comment by yuriyz** [comment]
Fixed
