### ISSUE TITLE
bug(jans-orm): npe in filter processor

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#1868]
**Describe the bug**

Try simple user authentication. NPE occurs. It seems to be related to recent ORM changes.
```
java.lang.NullPointerException: null
	at io.jans.orm.search.filter.FilterProcessor.excludeFilter(FilterProcessor.java:56) ~[jans-orm-filter-1.0.2-SNAPSHOT.jar:?]
	at io.jans.orm.search.filter.FilterProcessor.excludeFilter(FilterProcessor.java:37) ~[jans-orm-filter-1.0.2-SNAPSHOT.jar:?]
	at io.jans.orm.sql.impl.SqlEntryManager.excludeObjectClassFilters(SqlEntryManager.java:804) ~[jans-orm-sql-1.0.2-SNAPSHOT.jar:?]
	at io.jans.orm.sql.impl.SqlEntryManager.toSqlFilter(SqlEntryManager.java:789) ~[jans-orm-sql-1.0.2-SNAPSHOT.jar:?]
	at io.jans.orm.sql.impl.SqlEntryManager.findEntriesImpl(SqlEntryManager.java:478) ~[jans-orm-sql-1.0.2-SNAPSHOT.jar:?]
	at io.jans.orm.sql.impl.SqlEntryManager.findEntries(SqlEntryManager.java:395) ~[jans-orm-sql-1.0.2-SNAPSHOT.jar:?]
	at io.jans.orm.impl.BaseEntryManager.findEntries(BaseEntryManager.java:175) ~[jans-orm-core-1.0.2-SNAPSHOT.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at io.jans.orm.PersistenceEntryManager$EntityManager$2057902728$Proxy$_$$_WeldClientProxy.findEntries(Unknown Source) ~[jans-orm-core-1.0.2-SNAPSHOT.jar:?]
	at io.jans.as.common.service.common.UserService.getUser(UserService.java:92) ~[jans-auth-common-1.0.2-SNAPSHOT.jar:?]
	at io.jans.as.server.service.UserService$Proxy$_$$_WeldClientProxy.getUser(Unknown Source) ~[classes/:?]
	at io.jans.as.server.service.AuthenticationService.localAuthenticate(AuthenticationService.java:231) ~[classes/:?]
	at io.jans.as.server.service.AuthenticationService.authenticate(AuthenticationService.java:139) ~[classes/:?]
	at io.jans.as.server.service.AuthenticationService$Proxy$_$$_WeldClientProxy.authenticate(Unknown Source) ~[classes/:?]
	at io.jans.as.server.auth.Authenticator.userAuthenticationInteractive(Authenticator.java:456) ~[classes/:?]
	at io.jans.as.server.auth.Authenticator.authenticateImpl(Authenticator.java:225) ~[classes/:?]
```

**To Reproduce**
Try simple user authentication.

**Expected behavior**
Authentication must be successful.

**Comment by yuriyz** [comment]
Fixed.
