### ISSUE TITLE
fix:(jans-cli)(openbanking)unable to fetch script by name 

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1920]
**Describe the bug**
unable to fetch script by name 

**To Reproduce**
1. install jans with openbanking profile
2. access openbanking profile using jans-cli
3. select 6 for custom scripts then select 1 for get list of custom scripts and copy any script name
 4.select 4 to fetch customer scripts  and add name of sript copied above.

**Expected behavior**
should able to fetch script details using script name

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/181430417-3624e97c-1383-4d09-9758-11f5ba908c52.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 20.04

**Smartphone (please complete the following information):**

**Additional context**
getting below error in log
Traceback (most recent call last):
  File "/opt/jans/jans-cli/config-cli.py", line 2273, in main
    cli_object.runApp()
  File "/opt/jans/jans-cli/config-cli.py", line 2260, in runApp
    self.display_menu(self.menu)
  File "/opt/jans/jans-cli/config-cli.py", line 1854, in display_menu
    self.display_menu(menu.get_child(menu_numbering[int(selection)]))
  File "/opt/jans/jans-cli/config-cli.py", line 1857, in display_menu
    getattr(self, 'process_' + m.method)(m)
  File "/opt/jans/jans-cli/config-cli.py", line 1203, in process_get
    self.display_menu(endpoint.parent)
  File "/opt/jans/jans-cli/config-cli.py", line 1857, in display_menu
    getattr(self, 'process_' + m.method)(m)
  File "/opt/jans/jans-cli/config-cli.py", line 1134, in process_get
    api_caller = self.get_api_caller(endpoint)
  File "/opt/jans/jans-cli/config-cli.py", line 1430, in get_api_caller
    api_caller = getattr(api_instance, endpoint.info['operationId'].replace('-', '_'))
AttributeError: 'CustomScriptsApi' object has no attribute 'get_custom_script_by_name'

**Comment by devrimyatar** [comment]
Can't replicate. Probably fixed by swagger update

![image](https://user-images.githubusercontent.com/6398752/192727281-99858da3-bad4-414d-994a-88c8d70d4a6a.png)
