### ISSUE TITLE
fix(jans-config-api): issues in updating the default authentication method

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#2228]
## Updating the default authentication method

- unhandled NPE when providing null value for `/jans-config-api/api/v1/acrs` (which was the initial value)

  ```log
  26-08 07:45:39.953 INFO  jans.configapi.filters.LoggingFilter LoggingFilter.java:33- ****Request PUT /acrs from IP 176.199.211.208
  2022-08-26 07:45:39.970:WARN :oejs.HttpChannel:qtp762476028-147: /jans-config-api/api/v1/acrs
  org.jboss.resteasy.spi.UnhandledException: java.lang.NullPointerException
      at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:105)
      ...
  ```

- 500 error when updating `/jans-config-api/api/v1/acrs` with empty `DefaultAcr` value

  ```log
  2022-08-26 08:04:04.863:WARN :oejs.HttpChannel:qtp762476028-21: /jans-config-api/api/v1/acrs
  org.jboss.resteasy.spi.UnhandledException: jakarta.validation.ConstraintViolationException: 1 constraint violation(s) occurred during method validation.|Constructor or Method: public jakarta.ws.rs.core.Response io.jans.configapi.rest.resource.auth.AcrsResource.updateDefaultAuthenticationMethod(io.jans.configapi.rest.model.AuthenticationMethod)|Argument values: [AuthenticationMethod [ defaultAcr=]]|Constraint violations: | (1) Kind: PROPERTY| message: size must be between 1 and 2147483647| root bean: io.jans.configapi.rest.resource.auth.AcrsResource$Proxy$_$$_WeldSubclass@29f9777d| property path: updateDefaultAuthenticationMethod.authenticationMethod.defaultAcr| constraint: @jakarta.validation.constraints.Size(groups={}, min=1, message="{jakarta.validation.constraints.Size.message}", max=2147483647, payload={})
      at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:105)
      ...
  ```

Effectively, it is not possible for me to change the config back to it's original value.

**Comment by pujavs** [comment]
able to replicate this issue, working on the same

**Comment by pujavs** [comment]
Fixed via PR [2443](https://github.com/JanssenProject/jans/pull/2443)
Testing:  [Issue_2228.xlsx](https://github.com/JanssenProject/jans/files/9627765/Issue_2228.xlsx)
