### ISSUE TITLE
fix(jans-auth-server): Innocuous exception every time an authentication request is issued

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#2287]
I started noticing this weeks months ago. It is still there even in the latest release 1.0.2. 

Every time an auhtn request is launched in the browser (even with incognito), the log shows this error:

```
2022-08-31 21:33:09,158 ERROR [qtp1199673596-13] 9290a93b-3200-4031-a198-257eab73c749 [org.jboss.resteasy.core.ExceptionHandler] (ExceptionHandler.java:292) - RESTEASY002010: Failed to execute
jakarta.ws.rs.WebApplicationException: HTTP 302 Found
	at io.jans.as.server.authorize.ws.rs.AuthorizeRestWebServiceImpl.ifUserIsNull(AuthorizeRestWebServiceImpl.java:740) ~[classes/:?]
	at io.jans.as.server.authorize.ws.rs.AuthorizeRestWebServiceImpl.authorize(AuthorizeRestWebServiceImpl.java:372) ~[classes/:?]
	at io.jans.as.server.authorize.ws.rs.AuthorizeRestWebServiceImpl.requestAuthorization(AuthorizeRestWebServiceImpl.java:288) ~[classes/:?]
	at io.jans.as.server.authorize.ws.rs.AuthorizeRestWebServiceImpl.requestAuthorizationGet(AuthorizeRestWebServiceImpl.java:231) ~[classes/:?]
	at io.jans.as.server.authorize.ws.rs.AuthorizeRestWebServiceImpl$Proxy$_$$_WeldClientProxy.requestAuthorizationGet(Unknown Source) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170) ~[resteasy-core-6.0.0.Final.jar:6.0.0.Final]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130) ~[resteasy-core-6.0.0.Final.jar:6.0.0.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660) ~[resteasy-core-6.0.0.Final.jar:6.0.0.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524) ~[resteasy-core-6.0.0.Final.jar:6.0.0.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474) ~[resteasy-core-6.0.0.Final.jar:6.0.0.Final]
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364) ~[resteasy-core-6.0.0.Final.jar:6.0.0.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476) ~[resteasy-core-6.0.0.Final.jar:6.0.0.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434) ~[resteasy-core-6.0.0.Final.jar:6.0.0.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408) ~[resteasy-core-6.0.0.Final.jar:6.0.0.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69) ~[resteasy-core-6.0.0.Final.jar:6.0.0.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492) ~[resteasy-core-6.0.0.Final.jar:6.0.0.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261) ~[resteasy-core-6.0.0.Final.jar:6.0.0.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161) ~[resteasy-core-6.0.0.Final.jar:6.0.0.Final]
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364) ~[resteasy-core-6.0.0.Final.jar:6.0.0.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164) ~[resteasy-core-6.0.0.Final.jar:6.0.0.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247) ~[resteasy-core-6.0.0.Final.jar:6.0.0.Final]
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249) ~[resteasy-core-6.0.0.Final.jar:6.0.0.Final]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:60) ~[resteasy-core-6.0.0.Final.jar:6.0.0.Final]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55) ~[resteasy-core-6.0.0.Final.jar:6.0.0.Final]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587) ~[jetty-jakarta-servlet-api-5.0.2.jar:?]
``` 

However the authn process is proceeding correctly. I've seen this at least in debian and ubuntu 20

**Comment by yuriyz** [comment]
It's redirect web exception (normal flow). I guess better to no print it to not make confuse people with real exceptions.

**Comment by jgomer2001** [comment]
Hi @yuriyz , I installed today Jans, the noisy statement is still there in the log... can you re-check?

War file seems to be current:

```
root@host:/opt/dist/jans# /opt/amazon-corretto-11.0.15.9.1-linux-x64/bin/jar -xf jans-auth.war META-INF/MANIFEST.MF
root@host:/opt/dist/jans# cat META-INF/MANIFEST.MF 
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Created-By: Apache Maven 3.6.3
Built-By: jetty
Build-Jdk: 11.0.7
Implementation-Title: Jans authentication server
Implementation-Version: 1.0.3-SNAPSHOT
Implementation-Vendor-Id: io.jans
Build-Branch: 1a87dee13ea55ad28ff75c00e240499dae797a6c
Implementation-Build: 1a87dee13ea55ad28ff75c00e240499dae797a6c
```

**Comment by jgomer2001** [comment]
as of today, issue still there
