### ISSUE TITLE
fix(config-api): creating client via json and curl

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#2288]
I'm trying to create a new client with the following request:

```json
{
  "dn": "inum=1201.d52300ed-8193-510e-b31d-5829f4af346e,ou=clients,o=jans",
  "inum": "1201.d52300ed-8193-510e-b31d-5829f4af346e",
  "displayName": "",
  "clientSecret": "SEw7VOX8m9ah",
  "frontChannelLogoutUri": "null",
  "frontChannelLogoutSessionRequired": false,
  "registrationAccessToken": "",
  "clientIdIssuedAt": "",
  "clientSecretExpiresAt": "",
  "redirectUris": [
    "https://moabu-21f13b7c-9069-ad58-6020.gluu.info/.well-known/scim-configuration"
  ],
  "claimRedirectUris": [],
  "responseTypes": [],
  "grantTypes": [
    "client_credentials"
  ],
  "applicationType": "native",
  "contacts": [],
  "idTokenTokenBindingCnf": "",
  "clientName": {},
  "logoUri": {},
  "clientUri": {},
  "policyUri": {},
  "tosUri": {},
  "jwksUri": "",
  "jwks": "",
  "sectorIdentifierUri": "",
  "subjectType": "pairwise",
  "idTokenSignedResponseAlg": "",
  "idTokenEncryptedResponseAlg": "",
  "idTokenEncryptedResponseEnc": "",
  "userInfoSignedResponseAlg": "",
  "userInfoEncryptedResponseAlg": "",
  "userInfoEncryptedResponseEnc": "",
  "requestObjectSigningAlg": "",
  "requestObjectEncryptionAlg": "",
  "requestObjectEncryptionEnc": "",
  "tokenEndpointAuthMethod": "client_secret_basic",
  "tokenEndpointAuthSigningAlg": "",
  "defaultMaxAge": 0,
  "requireAuthTime": false,
  "defaultAcrValues": [],
  "initiateLoginUri": "",
  "postLogoutRedirectUris": [],
  "requestUris": [],
  "scopes": [],
  "claims": [],
  "trustedClient": false,
  "lastAccessTime": 0,
  "lastLogonTime": 0,
  "persistClientAuthorizations": false,
  "includeClaimsInIdToken": false,
  "refreshTokenLifetime": 0,
  "accessTokenLifetime": 0,
  "customAttributes": [
    {
      "name": "displayName",
      "multiValued": false,
      "values": [
        "SCIM client"
      ],
      "displayValue": "SCIM client",
      "value": "SCIM client"
    }
  ],
  "customObjectClasses": null,
  "rptAsJwt": false,
  "accessTokenAsJwt": false,
  "accessTokenSigningAlg": "RS256",
  "disabled": false,
  "authorizedOrigins": [],
  "softwareId": "",
  "softwareVersion": "",
  "softwareStatement": "",
  "attributes": {
    "tlsClientAuthSubjectDn": "",
    "runIntrospectionScriptBeforeAccessTokenAsJwtCreationAndIncludeClaims": false,
    "keepClientAuthorizationAfterExpiration": false,
    "allowSpontaneousScopes": false,
    "spontaneousScopes": null,
    "spontaneousScopeScriptDns": null,
    "updateTokenScriptDns": null,
    "backchannelLogoutUri": null,
    "backchannelLogoutSessionRequired": false,
    "additionalAudience": null,
    "postAuthnScripts": null,
    "consentGatheringScripts": null,
    "introspectionScripts": null,
    "rptClaimsScripts": null,
    "ropcScripts": null,
    "parLifetime": 600,
    "requirePar": false,
    "jansAuthSignedRespAlg": "",
    "jansAuthEncRespAlg": "",
    "jansAuthEncRespEnc": "",
    "jansSubAttr": "",
    "redirectUrisRegex": "",
    "jansAuthorizedAcr": null,
    "jansDefaultPromptLogin": false
  },
  "backchannelTokenDeliveryMode": "",
  "backchannelClientNotificationEndpoint": "",
  "backchannelAuthenticationRequestSigningAlg": "",
  "backchannelUserCodeParameter": "",
  "expirationDate": "",
  "deletable": false,
  "jansId": "",
  "description": "",
  "authenticationMethod": "client_secret_basic",
  "tokenBindingSupported": false,
  "baseDn": "inum=1201.d52300ed-8193-510e-b31d-5829f4af346e,ou=clients,o=jans"
}
```

When I send the request to the server, I get a 400 error. In the logs, I see the following stack trace: 

```
2022-08-23 06:40:06,191 ERROR [Scanner-0-1] [io.jans.orm.sql.impl.SqlEntryManager] (SqlEntryManager.java:865) - Failed to decode generalized time '2022-08-23T06:31'
java.time.format.DateTimeParseException: Text '2022-08-23T06:31Z' could not be parsed at index 16
        at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046) ~[?:?]
        at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948) ~[?:?]
        at java.time.Instant.parse(Instant.java:395) ~[?:?]
        at io.jans.orm.sql.impl.SqlEntryManager.decodeTime(SqlEntryManager.java:862) [jans-orm-sql-1.0.2-SNAPSHOT.jar:?]
        at io.jans.orm.sql.impl.SqlEntryManager.decodeTime(SqlEntryManager.java:851) [jans-orm-sql-1.0.2-SNAPSHOT.jar:?]
        at io.jans.orm.sql.impl.SqlEntryManager.decodeTime(SqlEntryManager.java:846) [jans-orm-sql-1.0.2-SNAPSHOT.jar:?]
        at io.jans.orm.impl.BaseEntryManager.setPropertyValue(BaseEntryManager.java:1873) [jans-orm-core-1.0.2-SNAPSHOT.jar:?]
        at io.jans.orm.impl.BaseEntryManager.createEntities(BaseEntryManager.java:1048) [jans-orm-core-1.0.2-SNAPSHOT.jar:?]
        at io.jans.orm.impl.BaseEntryManager.createEntities(BaseEntryManager.java:943) [jans-orm-core-1.0.2-SNAPSHOT.jar:?]
        at io.jans.orm.sql.impl.SqlEntryManager.createEntities(SqlEntryManager.java:587) [jans-orm-sql-1.0.2-SNAPSHOT.jar:?]
        at io.jans.orm.sql.impl.SqlEntryManager.createEntities(SqlEntryManager.java:551) [jans-orm-sql-1.0.2-SNAPSHOT.jar:?]
        at io.jans.orm.sql.impl.SqlEntryManager.findEntries(SqlEntryManager.java:401) [jans-orm-sql-1.0.2-SNAPSHOT.jar:?]
        at io.jans.orm.impl.BaseEntryManager.findEntries(BaseEntryManager.java:167) [jans-orm-core-1.0.2-SNAPSHOT.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor176.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) [weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) [weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
        at io.jans.orm.PersistenceEntryManager$EntityManager$722412412$Proxy$_$$_WeldClientProxy.findEntries(Unknown Source) [jans-orm-core-1.0.2-SNAPSHOT.jar:?]
        at io.jans.configapi.service.auth.ScopeService.searchScopesById(ScopeService.java:122) [classes/:?]
        at io.jans.configapi.service.auth.ScopeService$Proxy$_$$_WeldClientProxy.searchScopesById(Unknown Source) [classes/:?]
        at io.jans.configapi.security.api.ApiProtectionService.validateScope(ApiProtectionService.java:131) [classes/:?]
        at io.jans.configapi.security.api.ApiProtectionService.createScopeIfNeeded(ApiProtectionService.java:113) [classes/:?]
        at io.jans.configapi.security.api.ApiProtectionService.verifyResources(ApiProtectionService.java:72) [classes/:?]
        at io.jans.configapi.security.api.ApiProtectionService$Proxy$_$$_WeldClientProxy.verifyResources(Unknown Source) [classes/:?]
        at io.jans.configapi.configuration.AppInitializer.createAuthorizationService(AppInitializer.java:165) [classes/:?]
        at io.jans.configapi.configuration.AppInitializer.onStart(AppInitializer.java:102) [classes/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        ...
```

**Comment by pujavs** [comment]
@moabu, in json that you provided has `displayName` twice, once as root level attribute and one as customAttributes. Is this required?

**Comment by moabu** [comment]
> @moabu, in json that you provided has `displayName` twice, once as root level attribute and one as customAttributes. Is this required?

No, it's basically a possibility. If it's possible for the api to accept this then it should be considered. We are basically trying to pass in all the possible params . Unless this is just wrong in the eyes of the API it should be clarified .

**Comment by pujavs** [comment]
not sure why we would need an attribute at root level as well as a customAttribute. It is causing orm to fail, @yurem request you to please confirm.

**Comment by yurem** [comment]
Fixed. I've tested this functionality with MySQL and PostgreSQL. It works well in 1.0,.5 SNAPSHOT version.
