### ISSUE TITLE
fix: (jans-cli) unable to get attribute list 

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2457]
**Describe the bug**
unable to start jans-cli after device verification

**To Reproduce**
1. download "curl https://raw.githubusercontent.com/JanssenProject/jans/main/jans-linux-setup/jans_setup/install.py > install.py"
3. run command python3 install.py
4. add mandatory details
5. complete device verification
6. 1 and then to get attribute list

**Expected behavior**
should load attribute list

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/192079118-b077afab-f766-424c-bb1e-048f3bcbfba3.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 20

**Smartphone (please complete the following information):**

**Additional context**
error in log
Traceback (most recent call last):
  File "/opt/jans/jans-cli/config-cli.py", line 2314, in main
    cli_object.runApp()
  File "/opt/jans/jans-cli/config-cli.py", line 2301, in runApp
    self.display_menu(self.menu)
  File "/opt/jans/jans-cli/config-cli.py", line 1895, in display_menu
    self.display_menu(menu.get_child(menu_numbering[int(selection)]))
  File "/opt/jans/jans-cli/config-cli.py", line 1898, in display_menu
    getattr(self, 'process_' + m.method)(m)
  File "/opt/jans/jans-cli/config-cli.py", line 1219, in process_get
    self.display_menu(endpoint.parent)
  File "/opt/jans/jans-cli/config-cli.py", line 1893, in display_menu
    self.display_menu(menu.parent)
  File "/opt/jans/jans-cli/config-cli.py", line 1895, in display_menu
    self.display_menu(menu.get_child(menu_numbering[int(selection)]))
  File "/opt/jans/jans-cli/config-cli.py", line 1898, in display_menu
    getattr(self, 'process_' + m.method)(m)
  File "/opt/jans/jans-cli/config-cli.py", line 1209, in process_get
    self.tabular_data(tab_data, op_mode_endpoint)
  File "/opt/jans/jans-cli/config-cli.py", line 1111, in tabular_data
    row_.append(str(entry.get(header, '')))
AttributeError: 'str' object has no attribute 'get'

**Comment by devrimyatar** [comment]
Fixed in PR https://github.com/JanssenProject/jans/pull/2429
