### ISSUE TITLE
fix(jans-config-api):  GET configuser  exception

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#2473]
**Request:**
GET for `/jans-config-api/mgt/configuser`

**Stacktrace:**
```
26-09 14:56:15.490 INFO  jans.configapi.filters.LoggingFilter LoggingFilter.java:33- ****Request GET /configuser from IP 176.199.211.208
2022-09-26 14:56:15.497:WARN :oejs.HttpChannel:qtp762476028-13: handleException /jans-config-api/mgt/configuser com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.ArrayIndexOutOfBoundsException) (through reference chain: io.jans.configapi.plugin.mgt.rest.UserResource$UserPagedResult["entries"]->java.util.ArrayList[0]->io.jans.configapi.plugin.mgt.model.user.CustomUser["customAttributes"]->java.util.ArrayList[1]->io.jans.orm.model.base.CustomObjectAttribute["displayValue"])
```

**Comment by pujavs** [comment]
Working fine in LDAP but throwing the above error in MySQL. Attached logs and testing details
Analysing further
**LDAP Testing with latest code:**
![image](https://user-images.githubusercontent.com/43700552/192786346-3acd8120-db2d-400b-a1a3-edba38983901.png)

**MySQL Testing with latest code:**
![image](https://user-images.githubusercontent.com/43700552/192786422-c423b17a-a7b1-42d4-9bfa-d5a135ee35cb.png)


**Logs:**
Erroring out at

**Comment by pujavs** [comment]
**Issue:** `java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0`
	at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4351)
	`at io.jans.orm.model.base.CustomObjectAttribute.getDisplayValue(CustomObjectAttribute.java:95)`
	at io.jans.configapi.plugin.mgt.rest.UserResource.getUsers(UserResource.java:111)
	at io.jans.configapi.plugin.mgt.rest.UserResource$Proxy$_$$_WeldSubclass.getUsers(Unknown Source)
	at io.jans.configapi.plugin.mgt.rest.UserResource$Proxy$_$$_WeldClientProxy.getUsers(Unknown Source)

**Analysis:** CustomObjectAttribute values list attribute element accessed without checking length.

**Fix:** Added length check before accessing CustomObjectAttribute values list elements

**Module:**  jans-orm module

**Testing on My-SQL env:**
![image](https://user-images.githubusercontent.com/43700552/193061224-63f9fa77-f1d5-4614-a9fe-1cc1551e2542.png)
