### ISSUE TITLE
Config-api creating duplicate scope entries

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#294]
**Describe the bug**
When scaling or restarting config-api deployment, service immediately fails due to g duplicated scopes. The source of the duplication happens because setup injects the scopes and config-api seems to not honor that and recreate the scopes with new inums. This happens from start and the initial run of config-api has no apparent issues. However , as attached the ldap shows these duplicated scopes. 

| "Dn"                                                         | "jansId"                                                            |   |   |   |
|--------------------------------------------------------------|---------------------------------------------------------------------|---|---|---|
| "ou=scopes,o=jans"                                           |                                                                     |   |   |   |
| "inum=C17A,ou=scopes,o=jans"                                 | "address"                                                           |   |   |   |
| "inum=341A,ou=scopes,o=jans"                                 | "clientinfo"                                                        |   |   |   |
| "inum=764C,ou=scopes,o=jans"                                 | "email"                                                             |   |   |   |
| "inum=418e806a-efe8-468d-8820-bb21da43ecb2,ou=scopes,o=jans" | "https://jans.io/oauth/config/acrs.readonly"                        |   |   |   |
| "inum=1800.0D9CCC,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/acrs.readonly"                        |   |   |   |
| "inum=0549a8c9-fb9c-44d5-bde9-8e26ec4b922c,ou=scopes,o=jans" | "https://jans.io/oauth/config/acrs.write"                           |   |   |   |
| "inum=1800.B8DE82,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/acrs.write"                           |   |   |   |
| "inum=1800.36FC16,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/attributes.delete"                    |   |   |   |
| "inum=bc4c92db-f3be-4367-bc2b-0f9655154c05,ou=scopes,o=jans" | "https://jans.io/oauth/config/attributes.readonly"                  |   |   |   |
| "inum=1800.13AA0E,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/attributes.readonly"                  |   |   |   |
| "inum=0a03e651-1aae-4716-9233-26a0af054610,ou=scopes,o=jans" | "https://jans.io/oauth/config/attributes.write"                     |   |   |   |
| "inum=1800.A01874,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/attributes.write"                     |   |   |   |
| "inum=22b5211c-a257-4a85-83bb-2a9387bb84b5,ou=scopes,o=jans" | "https://jans.io/oauth/config/cache.readonly"                       |   |   |   |
| "inum=1800.45C56E,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/cache.readonly"                       |   |   |   |
| "inum=731d4c9b-d6c0-4164-917a-ea57f162cab0,ou=scopes,o=jans" | "https://jans.io/oauth/config/cache.write"                          |   |   |   |
| "inum=1800.F815D0,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/cache.write"                          |   |   |   |
| "inum=1800.419DD5,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/database/couchbase.delete"            |   |   |   |
| "inum=48d6994d-c6e2-4d3e-b003-e3210265e860,ou=scopes,o=jans" | "https://jans.io/oauth/config/database/couchbase.readonly"          |   |   |   |
| "inum=1800.3263EF,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/database/couchbase.readonly"          |   |   |   |
| "inum=03b564df-284c-4e52-b3d1-3c62288bfd7c,ou=scopes,o=jans" | "https://jans.io/oauth/config/database/couchbase.write"             |   |   |   |
| "inum=1800.B0C433,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/database/couchbase.write"             |   |   |   |
| "inum=1800.F4E351,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/database/ldap.delete"                 |   |   |   |
| "inum=c4e58bb2-5984-4581-aeb6-4fff3182643d,ou=scopes,o=jans" | "https://jans.io/oauth/config/database/ldap.readonly"               |   |   |   |
| "inum=1800.42C38F,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/database/ldap.readonly"               |   |   |   |
| "inum=c6dbc797-bc1a-4fd5-917d-1f7e1b45ac9c,ou=scopes,o=jans" | "https://jans.io/oauth/config/database/ldap.write"                  |   |   |   |
| "inum=1800.10F720,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/database/ldap.write"                  |   |   |   |
| "inum=75b058c1-9661-41a9-ae00-424d9f2dea23,ou=scopes,o=jans" | "https://jans.io/oauth/config/fido2.readonly"                       |   |   |   |
| "inum=1800.78D299,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/fido2.readonly"                       |   |   |   |
| "inum=e6f60355-c225-4088-bba6-72ea683e835b,ou=scopes,o=jans" | "https://jans.io/oauth/config/fido2.write"                          |   |   |   |
| "inum=1800.C38990,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/fido2.write"                          |   |   |   |
| "inum=fd02f59b-2575-4fb9-8607-39b786aaf2c0,ou=scopes,o=jans" | "https://jans.io/oauth/config/jwks.readonly"                        |   |   |   |
| "inum=1800.28FF8B,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/jwks.readonly"                        |   |   |   |
| "inum=fcfd0ac9-1cd1-4db9-82b9-95ef9eb2e678,ou=scopes,o=jans" | "https://jans.io/oauth/config/jwks.write"                           |   |   |   |
| "inum=1800.07C227,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/jwks.write"                           |   |   |   |
| "inum=af71f238-20a6-4843-ab25-e66c7278120e,ou=scopes,o=jans" | "https://jans.io/oauth/config/logging.readonly"                     |   |   |   |
| "inum=1800.CAA614,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/logging.readonly"                     |   |   |   |
| "inum=a5e32f7b-e654-4a09-9c09-ff13bf6e4ee2,ou=scopes,o=jans" | "https://jans.io/oauth/config/logging.write"                        |   |   |   |
| "inum=1800.4B522D,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/logging.write"                        |   |   |   |
| "inum=1800.FE975D,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/openid/clients.delete"                |   |   |   |
| "inum=33c8f9b7-4a3c-4849-88c1-7e4337687f18,ou=scopes,o=jans" | "https://jans.io/oauth/config/openid/clients.readonly"              |   |   |   |
| "inum=1800.9D4EBE,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/openid/clients.readonly"              |   |   |   |
| "inum=03648dc3-78bf-44e5-aa08-ab0d501c7d58,ou=scopes,o=jans" | "https://jans.io/oauth/config/openid/clients.write"                 |   |   |   |
| "inum=1800.3E6BA7,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/openid/clients.write"                 |   |   |   |
| "inum=1800.47E8E5,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/openid/sectoridentifiers.delete"      |   |   |   |
| "inum=308100a3-debe-44a5-ac1a-e236f0e2e3fc,ou=scopes,o=jans" | "https://jans.io/oauth/config/openid/sectoridentifiers.readonly"    |   |   |   |
| "inum=1800.70A20C,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/openid/sectoridentifiers.readonly"    |   |   |   |
| "inum=5cc862c5-1872-4930-89b2-46adc7508ada,ou=scopes,o=jans" | "https://jans.io/oauth/config/openid/sectoridentifiers.write"       |   |   |   |
| "inum=1800.F20BAA,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/openid/sectoridentifiers.write"       |   |   |   |
| "inum=1800.DCE0C3,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/scopes.delete"                        |   |   |   |
| "inum=9687cf73-55b0-4eaa-bb65-4c7dbe960423,ou=scopes,o=jans" | "https://jans.io/oauth/config/scopes.readonly"                      |   |   |   |
| "inum=1800.C0B661,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/scopes.readonly"                      |   |   |   |
| "inum=f686d4a6-05e3-42f1-ae34-85c4af7e75c2,ou=scopes,o=jans" | "https://jans.io/oauth/config/scopes.write"                         |   |   |   |
| "inum=1800.7FD3C9,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/scopes.write"                         |   |   |   |
| "inum=1800.79932F,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/scripts.delete"                       |   |   |   |
| "inum=d898ce7b-0439-4df9-a617-380adae3d4f8,ou=scopes,o=jans" | "https://jans.io/oauth/config/scripts.readonly"                     |   |   |   |
| "inum=1800.158007,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/scripts.readonly"                     |   |   |   |
| "inum=8a2d5088-549b-4d27-9b65-3a4c511cad35,ou=scopes,o=jans" | "https://jans.io/oauth/config/scripts.write"                        |   |   |   |
| "inum=1800.671341,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/scripts.write"                        |   |   |   |
| "inum=1800.05CA71,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/smtp.delete"                          |   |   |   |
| "inum=d1550788-ac11-4bc0-8e13-2226491e3e2c,ou=scopes,o=jans" | "https://jans.io/oauth/config/smtp.readonly"                        |   |   |   |
| "inum=1800.72FC9F,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/smtp.readonly"                        |   |   |   |
| "inum=906c39a9-f9aa-4749-9a15-1df11263d70d,ou=scopes,o=jans" | "https://jans.io/oauth/config/smtp.write"                           |   |   |   |
| "inum=1800.D2E431,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/smtp.write"                           |   |   |   |
| "inum=1800.B15085,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/uma/resources.delete"                 |   |   |   |
| "inum=f19f886b-8150-407c-be97-9071c906bf82,ou=scopes,o=jans" | "https://jans.io/oauth/config/uma/resources.readonly"               |   |   |   |
| "inum=1800.BDCE9B,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/uma/resources.readonly"               |   |   |   |
| "inum=9f0e44d1-9b07-43ce-8888-b48a1e469e12,ou=scopes,o=jans" | "https://jans.io/oauth/config/uma/resources.write"                  |   |   |   |
| "inum=1800.33641E,ou=scopes,o=jans"                          | "https://jans.io/oauth/config/uma/resources.write"                  |   |   |   |
| "inum=1800.4F4C08,ou=scopes,o=jans"                          | "https://jans.io/oauth/jans-auth-server/config/properties.readonly" |   |   |   |
| "inum=1800.61D3E9,ou=scopes,o=jans"                          | "https://jans.io/oauth/jans-auth-server/config/properties.write"    |   |   |   |
| "inum=1200.83383D,ou=scopes,o=jans"                          | "https://jans.io/scim/all-resources.search"                         |   |   |   |
| "inum=1200.0D9EB4,ou=scopes,o=jans"                          | "https://jans.io/scim/bulk"                                         |   |   |   |
| "inum=1200.57E5E9,ou=scopes,o=jans"                          | "https://jans.io/scim/fido.read"                                    |   |   |   |
| "inum=1200.D0F7EB,ou=scopes,o=jans"                          | "https://jans.io/scim/fido.write"                                   |   |   |   |
| "inum=1200.99AD30,ou=scopes,o=jans"                          | "https://jans.io/scim/fido2.read"                                   |   |   |   |
| "inum=1200.D5527D,ou=scopes,o=jans"                          | "https://jans.io/scim/fido2.write"                                  |   |   |   |
| "inum=1200.E14714,ou=scopes,o=jans"                          | "https://jans.io/scim/groups.read"                                  |   |   |   |
| "inum=1200.178DAF,ou=scopes,o=jans"                          | "https://jans.io/scim/groups.write"                                 |   |   |   |
| "inum=1200.2B7428,ou=scopes,o=jans"                          | "https://jans.io/scim/users.read"                                   |   |   |   |
| "inum=1200.0A0198,ou=scopes,o=jans"                          | "https://jans.io/scim/users.write"                                  |   |   |   |
| "inum=8A01,ou=scopes,o=jans"                                 | "mobile_phone"                                                      |   |   |   |
| "inum=C4F6,ou=scopes,o=jans"                                 | "offline_access"                                                    |   |   |   |
| "inum=F0C4,ou=scopes,o=jans"                                 | "openid"                                                            |   |   |   |
| "inum=6D90,ou=scopes,o=jans"                                 | "oxd"                                                               |   |   |   |
| "inum=C4F5,ou=scopes,o=jans"                                 | "permission"                                                        |   |   |   |
| "inum=D491,ou=scopes,o=jans"                                 | "phone"                                                             |   |   |   |
| "inum=43F1,ou=scopes,o=jans"                                 | "profile"                                                           |   |   |   |
| "inum=7D90,ou=scopes,o=jans"                                 | "revoke_session"                                                    |   |   |   |
| "inum=6D99,ou=scopes,o=jans"                                 | "uma_protection"                                                    |   |   |   |
| "inum=10B2,ou=scopes,o=jans"                                 | "user_name"                                                         |   |   |   |

Example:

Defined by config-api
```
objectclass: jansScope (structural)
objectclass: top (abstract)
displayName: https://jans.io/oauth/config/acrs.write
inum: 81b20775-ffea-4fc8-9138-96de65cb7bb8
jansAttrs: {"spontaneousClientId":null,"spontaneousClientScopes":null,"showInConfigurationEndpoint":true}
jansId: https://jans.io/oauth/config/acrs.write
jansScopeTyp: oauth
```

Defined in scopes.ldif
```
dn: inum=1800.B8DE82,ou=scopes,o=jans
description: Manage ACRS related information
displayName: Config API scope https://jans.io/oauth/config/acrs.write
inum: 1800.B8DE82
jansDefScope: false
jansId: https://jans.io/oauth/config/acrs.write
jansScopeTyp: oauth2
objectclass: top
objectclass: jansScope
```

**Screenshots**
Pod logs below after deployment restart.

```bash
INFO - jans.pycloudlib.wait - 2021-02-12 18:26:52,608 - Config is ready INFO - jans.pycloudlib.wait - 2021-02-12 18:26:52,637 - Secret is ready INFO - jans.pycloudlib.wait - 2021-02-12 18:26:53,022 - LDAP is ready
18:26:58 INFO  [io.ja.co.ConfigApiApplication] (main) =================================================================
18:26:58 INFO  [io.ja.co.ConfigApiApplication] (main) =============  STARTING API APPLICATION  ========================
18:26:58 INFO  [io.ja.co.ConfigApiApplication] (main) =================================================================
18:26:58 INFO  [io.ja.co.co.ConfigurationFactory] (main) Loading base configuration /etc/jans/conf/jans.properties
18:26:58 INFO  [io.ja.co.co.ConfigurationFactory] (main) Loaded base configuration:{certsDir=/etc/certs, fido2_ConfigurationEntryDN=ou=fido2,ou=configuration,o=jans, confDir=, jansAuth_ConfigurationEntryDN=ou=jans-auth,ou=configuration,o=jans, persistence.type=ldap, pythonModulesDir=/opt/jans/python/libs:/opt/jython/Lib/site-packages}
18:26:58 INFO  [io.ja.co.co.ConfigurationFactory] (main) Loading configuration from 'ldap' DB...
18:26:58 INFO  [io.ja.or.ld.op.im.LdapConnectionProvider] (main) Attempting to create connection pool: 1
18:26:59 INFO  [io.ja.or.ld.op.im.LdapConnectionProvider] (main) Attempting to create connection pool: 1
18:26:59 INFO  [io.ja.or.ld.op.im.LdapConnectionProvider] (main) Attempting to create connection pool: 1
18:26:59 INFO  [io.ja.or.ld.im.LdapEntryManagerFactory] (main) Created LdapEntryManager: io.jans.orm.ldap.operation.impl.LdapOperationServiceImpl@3f81621c
18:26:59 INFO  [io.ja.co.co.ConfigurationFactory] (main) Configuration loaded successfully.
18:26:59 INFO  [io.ja.co.co.ConfigurationFactory] (main) =============  createAuthorizationService() - ConfigurationFactory.getApiProtectionType() = oauth2
18:26:59 ERROR [io.ja.co.au.ConfigApiResourceProtectionService] (main) 2 Scope with same name.
18:26:59 ERROR [io.ja.co.co.ConfigurationFactory] (main) Failed to create AuthorizationService instance: javax.ws.rs.WebApplicationException: Multiple Scope with same name - https://jans.io/oauth/config/acrs.readonly
        at io.jans.configapi.auth.ConfigApiResourceProtectionService.createScopeIfNeeded(ConfigApiResourceProtectionService.java:105)
        at io.jans.configapi.auth.ConfigApiResourceProtectionService.verifyResources(ConfigApiResourceProtectionService.java:71)
```

**Additional context**
jans config build `2021-02-11 12:42`
Related issue : https://github.com/JanssenProject/jans-cloud-native/issues/19

**Comment by moabu** [comment]
Issue is stale. Later versions do not have this issue
