### ISSUE TITLE
fix(jans-tui): unable to launch jans-cli-tui after reinstall 

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3082]
**Describe the bug**
unable to launch jans-tui after reinstall 

**To Reproduce**
1. remove installed jans, it will also remove already installed jans-cli-tui 
2. reinstall jans 
3. wget https://github.com/JanssenProject/jans/archive/refs/heads/jans-cli-tui-works.zip
unzip jans-cli-tui-works.zip
cd jans-jans-cli-tui-works/jans-cli-tui/
make zipapp
./config-cli-tui.pyz

```
root@manojs1978-present-snipe:~/jans-jans-cli-tui-works/jans-cli-tui# ./config-cli-tui.pyz
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "./config-cli-tui.pyz/__main__.py", line 3, in <module>
  File "./config-cli-tui.pyz/_bootstrap/__init__.py", line 253, in bootstrap
  File "./config-cli-tui.pyz/_bootstrap/__init__.py", line 59, in import_string
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.shiv/config-cli-tui.pyz_c8d88dccabf9898375551e733112ec541460dae5b91565efcb992d2ff7ab6ff4/site-packages/cli_tui/jans_cli_tui.py", line 62, in <module>
    from cli import config_cli
  File "/root/.shiv/config-cli-tui.pyz_c8d88dccabf9898375551e733112ec541460dae5b91565efcb992d2ff7ab6ff4/site-packages/cli_tui/cli/config_cli.py", line 213, in <module>
    access_token = unobscure(config['DEFAULT']['access_token_enc'])
  File "/root/.shiv/config-cli-tui.pyz_c8d88dccabf9898375551e733112ec541460dae5b91565efcb992d2ff7ab6ff4/site-packages/cli_tui/cli/config_cli.py", line 95, in unobscure
    return decrypted.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 0: invalid start byte
```
**Expected behavior**
should not get any error in reinstall

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/203913674-d0d3d134-a7a9-4646-9178-a9ae607c280d.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser 
  - Version 20
  - DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Fixed in commit 8213541bcb9ca665b8c7542159e2b341d3514aa5
