### ISSUE TITLE
fix(jans-fido2): decoding authData incase of SuperGluu

### ISSUE THREAD

**Issue by maduvena** [JanssenProject/jans#3812]
U2F V1.2 spec needs to be checked to verify whether to use base64 or base64-URL to decode AuthData

Current error : 
```

7-02 13:38:44.645 DEBUG [qtp6519275-17] [jans.fido2.ws.rs.controller.AssertionController] (AssertionController.java:122) - Prepared U2F_V2 authentication options request: {"authenticateRequests":[{"type":"public-key","transports":["net","qr"],"appId":"https://maduvena-rational-jennet.gluu.info/.well-known/openid-configuration","userVerification":"preferred","challenge":"T6pUdkYhz_AGMxuDak6BWcR-I-lPkBF_lmtpccAfa60","keyHandle":"zq04MC8_3itYKRPO71L0ouoEGRKET-mO-r6IgooH3ZOVu2_n7w9mY4ykE51baDCQYmqObCmkXDXxsdNPNNs_WA","version":"U2F_V2"}]}
07-02 13:38:45.060 DEBUG [qtp6519275-16] [jans.fido2.ws.rs.controller.AssertionController] (AssertionController.java:136) - Finish authentication: username = madhu1, tokenResponse = {"signatureData":"AQAAAAEwRgIhANCfVml4Q31qQSxRWufPRYf5rKezPwWK01zwbzsZT0YmAiEA5_yZua9HaTfKwj1-e4Gv-aQhe8vmgRBDqcZ97YEygvg","clientData":"eyJ0eXAiOiJuYXZpZ2F0b3IuaWQuZ2V0QXNzZXJ0aW9uIiwiY2hhbGxlbmdlIjoiVDZwVWRrWWh6X0FHTXh1RGFrNkJXY1ItSS1sUGtCRl9sbXRwY2NBZmE2MCIsIm9yaWdpbiI6Imh0dHBzOlwvXC9tYWR1dmVuYS1yYXRpb25hbC1qZW5uZXQuZ2x1dS5pbmZvXC8ud2VsbC1rbm93blwvb3BlbmlkLWNvbmZpZ3VyYXRpb24ifQ","keyHandle":"zq04MC8_3itYKRPO71L0ouoEGRKET-mO-r6IgooH3ZOVu2_n7w9mY4ykE51baDCQYmqObCmkXDXxsdNPNNs_WA"}
07-02 13:38:45.061 DEBUG [qtp6519275-16] [jans.fido2.service.sg.converter.AssertionSuperGluuController] (AssertionSuperGluuController.java:218) - Prepared U2F_V2 assertion verify request: {"super_gluu_request":true,"super_gluu_request_mode":"two_step","type":"public-key","id":"zq04MC8_3itYKRPO71L0ouoEGRKET-mO-r6IgooH3ZOVu2_n7w9mY4ykE51baDCQYmqObCmkXDXxsdNPNNs_WA","rawId":"{\"signatureData\":\"AQAAAAEwRgIhANCfVml4Q31qQSxRWufPRYf5rKezPwWK01zwbzsZT0YmAiEA5_yZua9HaTfKwj1-e4Gv-aQhe8vmgRBDqcZ97YEygvg\",\"clientData\":\"eyJ0eXAiOiJuYXZpZ2F0b3IuaWQuZ2V0QXNzZXJ0aW9uIiwiY2hhbGxlbmdlIjoiVDZwVWRrWWh6X0FHTXh1RGFrNkJXY1ItSS1sUGtCRl9sbXRwY2NBZmE2MCIsIm9yaWdpbiI6Imh0dHBzOlwvXC9tYWR1dmVuYS1yYXRpb25hbC1qZW5uZXQuZ2x1dS5pbmZvXC8ud2VsbC1rbm93blwvb3BlbmlkLWNvbmZpZ3VyYXRpb24ifQ\",\"keyHandle\":\"zq04MC8_3itYKRPO71L0ouoEGRKET-mO-r6IgooH3ZOVu2_n7w9mY4ykE51baDCQYmqObCmkXDXxsdNPNNs_WA\"}","super_gluu_request_cancel":false,"response":{"clientDataJSON":"eyJ0eXBlIjoibmF2aWdhdG9yLmlkLmdldEFzc2VydGlvbiIsImNoYWxsZW5nZSI6IlQ2cFVka1loel9BR014dURhazZCV2NSLUktbFBrQkZfbG10cGNjQWZhNjAiLCJvcmlnaW4iOiJodHRwczpcL1wvbWFkdXZlbmEtcmF0aW9uYWwtamVubmV0LmdsdXUuaW5mb1wvLndlbGwta25vd25cL29wZW5pZC1jb25maWd1cmF0aW9uIn0","signature":"MEYCIQDQn1ZpeEN9akEsUVrnz0WH-aynsz8FitNc8G87GU9GJgIhAOf8mbmvR2k3ysI9fnuBr_mkIXvL5oEQQ6nGfe2BMoL4","authenticatorData":"5yMwp6fZzeofwqhvqq5vq/lO4O5nMO03ed/P/87RZl8BAAAAAQ==","attestationObject":"v_8"}}
07-02 13:38:45.062 DEBUG [qtp6519275-16] [io.jans.fido2.service.operation.AssertionService] (AssertionService.java:212) - authenticateResponse {"super_gluu_request":true,"super_gluu_request_mode":"two_step","type":"public-key","id":"zq04MC8_3itYKRPO71L0ouoEGRKET-mO-r6IgooH3ZOVu2_n7w9mY4ykE51baDCQYmqObCmkXDXxsdNPNNs_WA","rawId":"{\"signatureData\":\"AQAAAAEwRgIhANCfVml4Q31qQSxRWufPRYf5rKezPwWK01zwbzsZT0YmAiEA5_yZua9HaTfKwj1-e4Gv-aQhe8vmgRBDqcZ97YEygvg\",\"clientData\":\"eyJ0eXAiOiJuYXZpZ2F0b3IuaWQuZ2V0QXNzZXJ0aW9uIiwiY2hhbGxlbmdlIjoiVDZwVWRrWWh6X0FHTXh1RGFrNkJXY1ItSS1sUGtCRl9sbXRwY2NBZmE2MCIsIm9yaWdpbiI6Imh0dHBzOlwvXC9tYWR1dmVuYS1yYXRpb25hbC1qZW5uZXQuZ2x1dS5pbmZvXC8ud2VsbC1rbm93blwvb3BlbmlkLWNvbmZpZ3VyYXRpb24ifQ\",\"keyHandle\":\"zq04MC8_3itYKRPO71L0ouoEGRKET-mO-r6IgooH3ZOVu2_n7w9mY4ykE51baDCQYmqObCmkXDXxsdNPNNs_WA\"}","super_gluu_request_cancel":false,"response":{"clientDataJSON":"eyJ0eXBlIjoibmF2aWdhdG9yLmlkLmdldEFzc2VydGlvbiIsImNoYWxsZW5nZSI6IlQ2cFVka1loel9BR014dURhazZCV2NSLUktbFBrQkZfbG10cGNjQWZhNjAiLCJvcmlnaW4iOiJodHRwczpcL1wvbWFkdXZlbmEtcmF0aW9uYWwtamVubmV0LmdsdXUuaW5mb1wvLndlbGwta25vd25cL29wZW5pZC1jb25maWd1cmF0aW9uIn0","signature":"MEYCIQDQn1ZpeEN9akEsUVrnz0WH-aynsz8FitNc8G87GU9GJgIhAOf8mbmvR2k3ysI9fnuBr_mkIXvL5oEQQ6nGfe2BMoL4","authenticatorData":"5yMwp6fZzeofwqhvqq5vq/lO4O5nMO03ed/P/87RZl8BAAAAAQ==","attestationObject":"v_8"}}
07-02 13:38:45.067 DEBUG [qtp6519275-16] [io.jans.fido2.service.verifier.DomainVerifier] (DomainVerifier.java:49) - Domains comparison maduvena-rational-jennet.gluu.info https://maduvena-rational-jennet.gluu.info/.well-known/openid-configuration
07-02 13:38:45.071 DEBUG [qtp6519275-16] [io.jans.fido2.service.verifier.AssertionVerifier] (AssertionVerifier.java:52) - Authenticator data 5yMwp6fZzeofwqhvqq5vq/lO4O5nMO03ed/P/87RZl8BAAAAAQ==
2023-02-07 13:38:45.072:WARN :oejs.HttpChannel:qtp6519275-16: /jans-fido2/restv1/assertion/authentication
org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalArgumentException: Illegal base64 character 2f
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:105)
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:359)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)

Caused by:
java.lang.IllegalArgumentException: Illegal base64 character 2f
        at java.base/java.util.Base64$Decoder.decode0(Base64.java:746)
        at java.base/java.util.Base64$Decoder.decode(Base64.java:538)
        at io.jans.fido2.service.Base64Service.urlDecode(Base64Service.java:71)
        at io.jans.fido2.service.Base64Service$Proxy$_$$_WeldClientProxy.urlDecode(Unknown Source)
        at io.jans.fido2.service.AuthenticatorDataParser.parseAssertionData(AuthenticatorDataParser.java:74)
        at io.jans.fido2.service.AuthenticatorDataParser$Proxy$_$$_WeldClientProxy.parseAssertionData(Unknown Source)
        at io.jans.fido2.service.processor.assertion.U2FSuperGluuAssertionFormatProcessor.process(U2FSuperGluuAssertionFormatProcessor.java:87)
        at io.jans.fido2.service.processor.assertion.U2FSuperGluuAssertionFormatProcessor$Proxy$_$$_WeldClientProxy.process(Unknown Source)
        at io.jans.fido2.service.verifier.AssertionVerifier.verifyAuthenticatorAssertionResponse(AssertionVerifier.java:55)
        at io.jans.fido2.service.verifier.AssertionVerifier$Proxy$_$$_WeldClientProxy.verifyAuthenticatorAssertionResponse(Unknown Source)
        at io.jans.fido2.service.operation.AssertionService.verify(AssertionService.java:262)
        at io.jans.fido2.service.operation.AssertionService$Proxy$_$$_WeldClientProxy.verify(Unknown Source)
        at io.jans.fido2.service.sg.converter.AssertionSuperGluuController.finishAuthentication(AssertionSuperGluuController.java:220)
        at io.jans.fido2.service.sg.converter.AssertionSuperGluuController$Proxy$_$$_WeldClientProxy.finishAuthentication(Unknown Source)
        at io.jans.fido2.ws.rs.controller.AssertionController.finishAuthentication(AssertionController.java:138)
        at io.jans.fido2.ws.rs.controller.AssertionController$Proxy$_$$_WeldClientProxy.finishAuthentication(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by maduvena** [comment]
fix - https://github.com/JanssenProject/jans/pull/3815
