### ISSUE TITLE
fix(docker-jans-config-api): unable to find valid certification path to requested target on startup

### ISSUE THREAD

**Issue by iromli** [JanssenProject/jans#3866]
Running config-api with Google secretmanager throws the following errors:

```
config-api - 15-02 20:01:04.998 ERROR jans.configapi.filters.AuthorizationFilter AuthorizationFilter.java:94- ======AUTHORIZATION  FAILED ============
===============================                                                                                                                       
jakarta.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.secur
ity.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target                                        
        at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:321) ~[rest
easy-client-6.0.3.Final.jar:6.0.3.Final]                                                                                                              
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:494) ~[resteasy-client-6.0.3.Final.jar:6.0.3.Final] 
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152) ~[resteasy-client-6.0.3.Final.jar:6.0.3.Fin
al]
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115) ~[resteasy-client-6.0.3.Final.jar:6.0.3.Final]
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76) ~[resteasy-client-6.0.3.Final.jar:6.0.3.Final]
        at com.sun.proxy.$Proxy202.introspectToken(Unknown Source) ~[?:?]
        at io.jans.configapi.security.client.AuthClientFactory.getIntrospectionResponse(AuthClientFactory.java:65) ~[classes/:?]
        at io.jans.configapi.security.service.OpenIdService.getIntrospectionResponse(OpenIdService.java:58) ~[classes/:?]
        at io.jans.configapi.security.service.OpenIdService$Proxy$_$$_WeldClientProxy.getIntrospectionResponse(Unknown Source) ~[classes/:?]
        at io.jans.configapi.security.service.OpenIdAuthorizationService.processAuthorization(OpenIdAuthorizationService.java:101) ~[classes/:?]
        at io.jans.configapi.security.service.OpenIdAuthorizationService$Proxy$_$$_WeldClientProxy.processAuthorization(Unknown Source) ~[classes/:?]
        at io.jans.configapi.filters.AuthorizationFilter.filter(AuthorizationFilter.java:85) ~[classes/:?]
        at io.jans.configapi.filters.AuthorizationFilter$Proxy$_$$_WeldClientProxy.filter(Unknown Source) ~[classes/:?]
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:312) ~[resteasy-core
-6.0.3.Final.jar:6.0.3.Final]

```

**Comment by iromli** [comment]
The issue was caused by incorrect cert used by ingress.
