### ISSUE TITLE
fix(jans-auth-server): mismatch in notation used for `SmtpConfiguration`

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#4581]
I've been facing this issue when trying to send e-mail via `MailService#send` method:

```
Caused by: io.jans.orm.exception.MappingException: Failed to convert json value '{
    "trust_host": true,
    "connect_protection": "SslTls",
    "host": "xxx.gluu.org",
    "port": yyy,
    "smtp_authentication_account_username": "myuser@gluu.org",
    "from_name": "Jose",
    "from_email_address": "myuser@gluu.org",
    "requires_authentication": true,
    "smtp_authentication_account_password":"myencodedpassword"
}' to object of type class io.jans.model.SmtpConfiguration
	at io.jans.orm.impl.BaseEntryManager.convertJsonToValue(BaseEntryManager.java:1993) ~[jans-orm-core-1.0.12-SNAPSHOT.jar:?]
	at io.jans.orm.impl.BaseEntryManager.setPropertyValue(BaseEntryManager.java:1915) ~[jans-orm-core-1.0.12-SNAPSHOT.jar:?]
	at io.jans.orm.impl.BaseEntryManager.createEntities(BaseEntryManager.java:1029) ~[jans-orm-core-1.0.12-SNAPSHOT.jar:?]
	at io.jans.orm.impl.BaseEntryManager.createEntities(BaseEntryManager.java:924) ~[jans-orm-core-1.0.12-SNAPSHOT.jar:?]
	at io.jans.orm.impl.BaseEntryManager.find(BaseEntryManager.java:705) ~[jans-orm-core-1.0.12-SNAPSHOT.jar:?]
	at io.jans.orm.impl.BaseEntryManager.find(BaseEntryManager.java:581) ~[jans-orm-core-1.0.12-SNAPSHOT.jar:?]
	at io.jans.orm.impl.BaseEntryManager.find(BaseEntryManager.java:568) ~[jans-orm-core-1.0.12-SNAPSHOT.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor90.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at io.jans.orm.PersistenceEntryManager$EntityManager$2057902728$Proxy$_$$_WeldClientProxy.find(Unknown Source) ~[jans-orm-core-1.0.12-SNAPSHOT.jar:?]
	at io.jans.as.common.service.common.ConfigurationService.getConfiguration(ConfigurationService.java:82) ~[jans-auth-common-1.0.12-SNAPSHOT.jar:?]
	at io.jans.as.common.service.common.ConfigurationService$Proxy$_$$_WeldClientProxy.getConfiguration(Unknown Source) ~[jans-auth-common-1.0.12-SNAPSHOT.jar:?]
	at io.jans.as.common.service.common.ApplicationFactory.getSmtpConfiguration(ApplicationFactory.java:96) ~[jans-auth-common-1.0.12-SNAPSHOT.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
```

As shown above, the `jansSmtpConf` attribute under `ou=configuration,o=jans` uses the underscore notation instead of camel case.

Bean `io.jans.model.SmtpConfiguration` has `@JsonProperty` annotations with underscores for its fields.

When orm tries to convert the raw json content into an instance of `SmtpConfiguration` it does not follow the jackson annotations but field names and thus the exception above is shown. 

I was able to verify this because I changed my `jansSmtpConf` temporarily to:

```
{
    "serverTrust": true,
    "connectProtection": "SslTls",
    "host": "webmail.gluu.org",
    "port": 587,
    "smtpAuthenticationAccountUsername": "myuser@gluu.org",
    "fromName": "Jose",
    "fromEmailAddress": "myuser@gluu.org",
    "requiresAuthentication": true,
    "smtpAuthenticationAccountPassword":"myencodedpassword"
}
```

and the exception was gone.

I now get another exception, which we can investigate later, but at least the `sendMethod` is actually called:

```
2023-04-13 13:43:51,794 DEBUG [qtp952562199-16] fe8f0c1e-ece8-4095-af6c-aaf4e561a203 [io.jans.service.MailService] (MailService.java:167) - Host name: xxx.gluu.org, port: yyy, connection time out: 5000
2023-04-13 13:43:51,911 ERROR [qtp952562199-16] fe8f0c1e-ece8-4095-af6c-aaf4e561a203 [io.jans.service.MailService] (MailService.java:289) - Failed to send message
com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.0 Must issue a STARTTLS command first

	at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2374) ~[jakarta.mail-1.6.7.jar:1.6.7]
	at com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1808) ~[jakarta.mail-1.6.7.jar:1.6.7]
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1285) ~[jakarta.mail-1.6.7.jar:1.6.7]
	at javax.mail.Transport.send0(Transport.java:231) ~[jakarta.mail-1.6.7.jar:1.6.7]
	at javax.mail.Transport.send(Transport.java:100) ~[jakarta.mail-1.6.7.jar:1.6.7]
	at io.jans.service.MailService.sendMail(MailService.java:287) ~[jans-core-service-1.0.12-SNAPSHOT.jar:?]
	at io.jans.service.MailService.sendMail(MailService.java:144) ~[jans-core-service-1.0.12-SNAPSHOT.jar:?]
	at io.jans.service.MailService$Proxy$_$$_WeldClientProxy.sendMail(Unknown Source) ~[jans-core-service-1.0.12-SNAPSHOT.jar:?]

```

Once a solution is agreed, let's please ensure file `./jans/jans-config-api/docs/jans-config-api-swagger.yaml` is updated accordingly, @pujavs can help here

Also we have to update the value used for `jansSmtpConf` attribute in a default installation if required, currently it uses underscores.

**Comment by smansoft** [comment]
```
    "connectProtection": "SslTls",
    "port": 587,
```
587 - smtp (STARTTLS)
465 - smtp (SSL/TLS)
It's necessary to use:
```
    "connectProtection": "StartTls"
```
.

**Comment by yurem** [comment]
ORM here not call SmtpConnectProtectionType.resolveByValue because `connect_protection` is internal JSON property. ORM call this method only if the attribute have enum type.

**Comment by yurem** [comment]
For this case we need to instruct JSON deserializer to use special method to map value to enum.
