### ISSUE TITLE
wget-based demo setup fails

### ISSUE THREAD

**Issue by jernst** [JanssenProject/jans#4601]
Brand-new Ubuntu VM on aarch64 / Mac M1 running under Parallels. Updated to latest as of today.

Running the wget etc command in QuickStart in the README.md fails with a 
```
ImportError: /opt/jans/jans-setup/setup_app/pylib/cryptography/hazmat/bindings/_rust.abi3.so: cannot open shared object file: No such file or directory
```
Longer partial transcript:

```
 *****   Running the setup script for Janssen!!   *****
*****   PLEASE NOTE THAT THIS MAY TAKE A WHILE TO FINISH. PLEASE BE PATIENT!!   *****
Executing https://raw.githubusercontent.com/JanssenProject/jans/a9b3eabf749cc5dde98c12ffa1b9a1bb9a8091f6/jans-linux-setup/jans_setup/install.py > install.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10042  100 10042    0     0  28092      0 --:--:-- --:--:-- --:--:-- 28128
Executing python3 install.py -yes --args=-f setup.properties -n -test-client-id=9876baac-de39-4c23-8a78-674b59df8c09 -test-client-secret=1t5Fin3#security --test-client-trusted
//install.py:58: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils import dist
Downloading https://github.com/sqlalchemy/sqlalchemy/archive/rel_1_3_23.zip to /tmp/tmphi6gzcbx/rel_1_3_23.zip
Download size: 3637021 bytes
Downloading https://files.pythonhosted.org/packages/20/8b/66600f5851ec7893ace9b74445d7eaf3499571b347e339d18c76c876b0f9/cryptography-37.0.4-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl to /tmp/tmpgl3re584/cryptography-37.0.4-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Download size: 4151466 bytes
Downloading https://github.com/jpadilla/pyjwt/archive/refs/tags/2.4.0.zip to /tmp/tmplxec7pn8/2.4.0.zip
Download size: 87283 bytes
The following packages are required for Janssen Server
apache2 wget xz-utils unzip rsyslog bzip2 python3-urllib3 python3-certifi python3-requests python3-ruamel.yaml python3-pymysql python3-certifi
Installing packages apache2 wget xz-utils unzip rsyslog bzip2 python3-urllib3 python3-certifi python3-requests python3-ruamel.yaml python3-pymysql python3-certifi
Traceback (most recent call last):
  File "/opt/jans/jans-setup/setup.py", line 110, in <module>
    from setup_app.test_data_loader import TestDataLoader
  File "/opt/jans/jans-setup/setup_app/test_data_loader.py", line 16, in <module>
    from setup_app.installers.base import BaseInstaller
  File "/opt/jans/jans-setup/setup_app/installers/base.py", line 10, in <module>
    from setup_app.utils.db_utils import dbUtils
  File "/opt/jans/jans-setup/setup_app/utils/db_utils.py", line 24, in <module>
    from setup_app.utils.spanner_rest_client import SpannerClient
  File "/opt/jans/jans-setup/setup_app/utils/spanner_rest_client.py", line 4, in <module>
    import jwt
  File "/opt/jans/jans-setup/setup_app/pylib/jwt/__init__.py", line 1, in <module>
    from .api_jwk import PyJWK, PyJWKSet
  File "/opt/jans/jans-setup/setup_app/pylib/jwt/api_jwk.py", line 3, in <module>
    from .algorithms import get_default_algorithms
  File "/opt/jans/jans-setup/setup_app/pylib/jwt/algorithms.py", line 6, in <module>
    from .utils import (
  File "/opt/jans/jans-setup/setup_app/pylib/jwt/utils.py", line 7, in <module>
    from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve
  File "/opt/jans/jans-setup/setup_app/pylib/cryptography/hazmat/primitives/asymmetric/ec.py", line 13, in <module>
    from cryptography.hazmat.primitives.asymmetric import (
  File "/opt/jans/jans-setup/setup_app/pylib/cryptography/hazmat/primitives/asymmetric/utils.py", line 6, in <module>
    from cryptography.hazmat.bindings._rust import asn1
ImportError: /opt/jans/jans-setup/setup_app/pylib/cryptography/hazmat/bindings/_rust.abi3.so: cannot open shared object file: No such file or directory
Downloading https://github.com/JanssenProject/jans/archive/refs/heads/main.zip as /opt/dist/jans/jans.zip
Extracting jans-setup package
Launching Janssen Setup
Executing /usr/bin/python3 /opt/jans/jans-setup/setup.py -f setup.properties -n
*****   Setup script completed!!    *****
 * Starting Apache httpd web server apache2
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
 * 
/app/scripts/entrypoint.sh: line 86: /opt/dist/scripts/jans-auth: No such file or directory
Janssen Authorization has already been installed. Starting services...
```

**Comment by nynymike** [comment]
I didn't think m1 is a supporter platform....

**Comment by moabu** [comment]
At the moment we only support amd64.

**Comment by jernst** [comment]
* Nothing in the README.me says that aarch64 isn't a supported platform: "For development and testing purposes, the Janssen Server can be quickly installed on an Ubuntu 20.04 VM by running the command below..." Which is what I tried.
* Developers love Apple laptops, and it's hard to even buy an x86_64 Apple laptop any more.

So I guess there are two issues here:

* short term: clearly indicate that the demo wget script is only supposed to be run on Ubuntu x86_64, otherwise people like me end up spending a bunch of time and accomplish nothing
* medium term: make it work on Apple laptops and document how to run it.

**Comment by moabu** [comment]
Hey @jernst ,


Yea that's an excellent suggestion . Thanks for opening the issue . We will open an issue to have this work with Mac and I will tag this issue so you can follow it.

**Comment by nynymike** [comment]
Yes, it would be nice to have at least one VM distribution that works on M1. But we should document that it doesn't it exist yet in the short term.

**Comment by moabu** [comment]
Images arch has been updated. We recommend using an isolated environment when testing such as https://mac.getutm.app
