### ISSUE TITLE
fix(jans-orm): npe in SqlFilterConverter

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#4775]
**Describe the bug**

```
2023-05-02 13:13:34,322 INFO  [qtp371800738-13] 575c87af-67ce-40e0-931b-678298d0cb0a [as.server.authorize.ws.rs.DeviceAuthorizationAction] (DeviceAuthorizationAction.java:230) - Redirecting to authorization code flow to process device authorization, data: DeviceAuthorizationCacheControl{userCode='KVXW-KVKM', deviceCode='fb8cfb7b1223f18eaa9eb0e3351c238b73c458e38a53734b', client=DeletableEntity{expirationDate=null, deletable=false} BaseEntry [dn=inum=2000.3740a5f1-50a0-4852-aca3-b08afe8d72ef,ou=clients,o=jans], scopes=[openid, profile, offline_access, email], verificationUri='https://test-gluu-jans.gluu.info/device-code', expiresIn=1800, interval=5, lastAccessControl=1683033185269, status=PENDING}
2023-05-02 13:13:58,835 ERROR [qtp371800738-17] 791b1a6d-af27-4ab0-b61d-9e0210d4a0e7 [io.jans.as.server.auth.Authenticator] (Authenticator.java:239) - null
java.lang.NullPointerException: null
	at io.jans.orm.sql.impl.SqlFilterConverter.prepareTypedExpressionValue(SqlFilterConverter.java:498) ~[jans-orm-sql-1.0.13-SNAPSHOT.jar:?]
	at io.jans.orm.sql.impl.SqlFilterConverter.buildTypedExpression(SqlFilterConverter.java:453) ~[jans-orm-sql-1.0.13-SNAPSHOT.jar:?]
	at io.jans.orm.sql.impl.SqlFilterConverter.convertToSqlFilterImpl(SqlFilterConverter.java:201) ~[jans-orm-sql-1.0.13-SNAPSHOT.jar:?]
	at io.jans.orm.sql.impl.SqlFilterConverter.convertToSqlFilter(SqlFilterConverter.java:87) ~[jans-orm-sql-1.0.13-SNAPSHOT.jar:?]
	at io.jans.orm.sql.impl.SqlFilterConverter.convertToSqlFilter(SqlFilterConverter.java:82) ~[jans-orm-sql-1.0.13-SNAPSHOT.jar:?]
	at io.jans.orm.sql.impl.SqlFilterConverter.convertToSqlFilter(SqlFilterConverter.java:78) ~[jans-orm-sql-1.0.13-SNAPSHOT.jar:?]
	at io.jans.orm.sql.impl.SqlEntryManager.toSqlFilter(SqlEntryManager.java:808) ~[jans-orm-sql-1.0.13-SNAPSHOT.jar:?]
	at io.jans.orm.sql.impl.SqlEntryManager.findEntriesImpl(SqlEntryManager.java:478) ~[jans-orm-sql-1.0.13-SNAPSHOT.jar:?]
	at io.jans.orm.sql.impl.SqlEntryManager.findEntries(SqlEntryManager.java:393) ~[jans-orm-sql-1.0.13-SNAPSHOT.jar:?]
	at io.jans.orm.impl.BaseEntryManager.findEntries(BaseEntryManager.java:158) ~[jans-orm-core-1.0.13-SNAPSHOT.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at io.jans.orm.PersistenceEntryManager$EntityManager$2057902728$Proxy$_$$_WeldClientProxy.findEntries(Unknown Source) ~[jans-orm-core-1.0.13-SNAPSHOT.jar:?]
	at io.jans.as.common.service.common.UserService.getUser(UserService.java:92) ~[jans-auth-common-1.0.13-SNAPSHOT.jar:?]
	at io.jans.as.server.service.UserService$Proxy$_$$_WeldClientProxy.getUser(Unknown Source) ~[classes/:?]
	at io.jans.as.server.service.AuthenticationService.localAuthenticate(AuthenticationService.java:231) ~[classes/:?]
	at io.jans.as.server.service.AuthenticationService.authenticate(AuthenticationService.java:139) ~[classes/:?]
	at io.jans.as.server.service.AuthenticationService$Proxy$_$$_WeldClientProxy.authenticate(Unknown Source) ~[classes/:?]
	at io.jans.as.server.auth.Authenticator.userAuthenticationInteractive(Authenticator.java:459) ~[classes/:?]
	at io.jans.as.server.auth.Authenticator.authenticateImpl(Authenticator.java:227) ~[classes/:?]
	at io.jans.as.server.auth.Authenticator.authenticate(Authenticator.java:139) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
```

**Comment by yurem** [comment]
Fixed
