### ISSUE TITLE
fix (jans-config-api) : jans-config-api is not working properly.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [JanssenProject/jans#4847]
**Describe the bug**
 jans-config-api is not working properly.

**To Reproduce**
1. Install jans-server.
2. Run jans-TUI.
3. try to change tabs.

**Expected behavior**

 user must be able to change tabs in Jans-TUI. 

**Actual behavior**

getting 503 error on config-api.

**Screenshots**

![Screenshot (52)](https://user-images.githubusercontent.com/34593983/236819855-ef7a4388-c9e7-47c5-a4a4-f6bf5b78bedc.png)

**Desktop (please complete the following information):**
  - OS: RHEL8
  - Browser chrome
  - Version  jans-server 1.0.13 nightly

**Log**

` 08-05 11:38:05.373 INFO  weld.environment.jetty.JettyContainer JettyContainer.java:88- WELD-ENV-001212: Jetty CdiDecoratingListener support detected, CDI injection will be available in Listeners, Servlets and Filters.
2023-05-08 11:38:06.747:WARN :oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@4ff8d125{jans-config-api.xml,/jans-config-api,[file:///opt/jetty-11.0/temp/jetty-localhost-8074-jans-config-api_war-_jans-config-api-any-2825278490185733918/webapp/, jar:file:///opt/jans/jetty/jans-config-api/custom/libs/scim-plugin.jar!/META-INF/resources, jar:file:///opt/jetty-11.0/temp/jetty-localhost-8074-jans-config-api_war-_jans-config-api-any-2825278490185733918/webapp/WEB-INF/lib/jakarta.faces-3.0.2.jar!/META-INF/resources],UNAVAILABLE}{/opt/jans/jetty/jans-config-api/webapps/jans-config-api.war}
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type MailService with qualifiers @Default|  at injection point [UnbackedAnnotatedField] @Inject private io.jans.configapi.rest.resource.auth.ConfigSmtpResource.mailService|  at io.jans.configapi.rest.resource.auth.ConfigSmtpResource.mailService(ConfigSmtpResource.java:0)|WELD-001474: Class io.jans.service.MailService is on the classpath, but was ignored because a class it references was not found: javax.mail.Authenticator.|
        at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:378)
        at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:290)
        at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:143)
        at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:164)
        at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:526)
        at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:64)
        at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:62)
        at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
        at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
2023-05-08 11:38:06.764:INFO :oejs.AbstractConnector:main: Started ServerConnector@3b50f432{HTTP/1.1, (http/1.1)}{localhost:8074}
2023-05-08 11:38:06.770:INFO :oejs.Server:main: Started Server@27912e3{STARTING}[11.0.15,sto=5000] @12288ms 
`

**Comment by pujavs** [comment]
Post analysis found issue with `jakarta.mail` version change to `2.0.1` while JDK upgrade to 17

**Comment by pujavs** [comment]
This was closed yesterday via PR #4853
