### ISSUE TITLE
fix: failed to initialize resteasy proxy from script at server startup

### ISSUE THREAD

**Issue by yurem** [JanssenProject/jans#5116]
**Describe the bug**
jans-auth-server/oxauth can't initialize Resteasy Proxy from script at startup.

**To Reproduce**
1. Enable SG script
2. Restart jans-auth-server/oxauth
3. Open script log and scroll to java.lang.RuntimeException
5. Increase script version to reload script
6. This time server will load script without issues.

**Expected behavior**
No issues with Resteasy Proxy at server startup

**Screenshots**
```
(PythonService.java:244) -  java.lang.RuntimeException: java.lang.ClassNotFoundException: org.jboss.resteasy.client.jaxrs.internal.proxy.ProxyBuilderImpl
```

**Additional context**
Full stack trace from debugger:
```
java.lang.ClassNotFoundException: org.jboss.resteasy.client.jaxrs.internal.proxy.ProxyBuilderImpl
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.jboss.resteasy.client.jaxrs.ProxyBuilder.builder(ProxyBuilder.java:35)
	at org.jboss.resteasy.client.jaxrs.internal.ClientWebTarget.createProxyBuilder(ClientWebTarget.java:107)
	at org.jboss.resteasy.client.jaxrs.internal.ClientWebTarget.proxy(ClientWebTarget.java:94)
	at org.gluu.oxnotify.client.NotifyClientFactory.createMetaDataConfigurationService(NotifyClientFactory.java:47)

...
```
The issue is in [org.jboss.resteasy.client.jaxrs.ProxyBuilder.builder](https://github.com/resteasy/resteasy/blob/4.7/resteasy-client-api/src/main/java/org/jboss/resteasy/client/jaxrs/ProxyBuilder.java#L35). At this line it attempts to load class with `jdk.internal.loader.ClassLoaders$AppClassLoader` which it gets from Thread.currentThread().getContextClassLoader()

At this place we need to use `WebAppClassLoader` to load this class.

**Comment by yuriyz** [comment]
Issue is resolved in https://github.com/JanssenProject/jans/pull/5118
