### ISSUE TITLE
bug (auth server): Failed to persist session entity

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#5807]
Testing Jans 1.0.16... I see this in the logs... 

```
2023-08-08 14:27:35,605 ERROR [qtp210506412-17] [io.jans.as.server.service.SessionIdService] (SessionIdService.java:586) - Failed to persist entry: 'jansId=ec8e2e89-5ef8-4df8-894f-b27dd3a4c075,ou=sessions,o=jans'
io.jans.orm.exception.EntryPersistenceException: Failed to persist entry: 'jansId=ec8e2e89-5ef8-4df8-894f-b27dd3a4c075,ou=sessions,o=jans'
        at io.jans.orm.sql.impl.SqlEntryManager.persist(SqlEntryManager.java:217) ~[jans-orm-sql-1.0.16.jar:?]
        at io.jans.orm.impl.BaseEntryManager.persist(BaseEntryManager.java:115) ~[jans-orm-core-1.0.16.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
. . .
Caused by: io.jans.orm.exception.operation.PersistenceException: Failed to add entry
        at io.jans.orm.sql.operation.impl.SqlOperationServiceImpl.addEntryImpl(SqlOperationServiceImpl.java:213) ~[jans-orm-sql-1.0.16.jar:?]
        at io.jans.orm.sql.operation.impl.SqlOperationServiceImpl.addEntry(SqlOperationServiceImpl.java:177) ~[jans-orm-sql-1.0.16.jar:?]
        at io.jans.orm.sql.impl.SqlEntryManager.persist(SqlEntryManager.java:212) ~[jans-orm-sql-1.0.16.jar:?]
        ... 95 more
Caused by: com.querydsl.core.QueryException: Caught SQLIntegrityConstraintViolationException for insert into jansdb.jansSessId (authnTime, creationDate, del, exp, jansId, jansLastAccessTime, sid, jansPermissionGrantedMap, jansSessAttr, jansSessState, jansState, jansUsrDN, objectClass, dn, doc_id)
values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
. . .
       at io.jans.orm.sql.impl.SqlEntryManager.persist(SqlEntryManager.java:212) ~[jans-orm-sql-1.0.16.jar:?]
        ... 95 more
```

**Comment by yuriyz** [comment]
@yurem it is something with schema, right ?

**Comment by yurem** [comment]
@nynymike Can you add full stack trace? At the end of it will can find root SQL cause. Probably the issue in column length.

**Comment by yuriyz** [comment]
Sounds like issue is gone. Closing this ticket. If it's still reproducible please attach full `jans-auth.log` file and re-open.
