### ISSUE TITLE
fix(jans-cli-tui): CLU TUI build errors

### ISSUE THREAD

**Issue by devrimyatar** [JanssenProject/jans#5835]
- [x] On OpenSUSE:

```
Traceback (most recent call last):
  File "/root/jans-main/jans-cli-tui/./jans-cli-tui.pyz/_bootstrap/__init__.py", line 84, in import_string
AttributeError: module 'cli_tui' has no attribute 'jans_cli_tui'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/root/jans-main/jans-cli-tui/./jans-cli-tui.pyz/__main__.py", line 3, in <module>
  File "/root/jans-main/jans-cli-tui/./jans-cli-tui.pyz/_bootstrap/__init__.py", line 253, in bootstrap
  File "/root/jans-main/jans-cli-tui/./jans-cli-tui.pyz/_bootstrap/__init__.py", line 81, in import_string
  File "/root/jans-main/jans-cli-tui/./jans-cli-tui.pyz/_bootstrap/__init__.py", line 87, in import_string
ImportError: module 'cli_tui' has no attribute 'jans_cli_tui'
```
 - [x] On Ubuntu:

```
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "./jans-cli-tui.pyz/__main__.py", line 3, in <module>
  File "./jans-cli-tui.pyz/_bootstrap/__init__.py", line 253, in bootstrap
  File "./jans-cli-tui.pyz/_bootstrap/__init__.py", line 59, in import_string
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mbaser/.shiv/jans-cli-tui.pyz_8aa146e64c8813d058804eb3865d968ddb3ef7a8d3bb62632c13e801ffee981b/site-packages/cli_tui/jans_cli_tui.py", line 32, in <module>
    from cli import config_cli
  File "/home/mbaser/.shiv/jans-cli-tui.pyz_8aa146e64c8813d058804eb3865d968ddb3ef7a8d3bb62632c13e801ffee981b/site-packages/cli_tui/cli/config_cli.py", line 212, in <module>
    host = config['DEFAULT']['jans_host']
  File "/usr/lib/python3.8/configparser.py", line 1254, in __getitem__
    raise KeyError(key)
KeyError: 'jans_host'
```

**Comment by devrimyatar** [comment]
OpenSUSE is missing python3 altough there is such command, had to install python3:
`zypper install python3`
