### ISSUE TITLE
feat(jans-auth-server): JIT compiler fails under jvm 17 (works perfectly under jvm 11)

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#5837]
### Description

JIT compiler fails under jvm 17 (works perfectly under jvm 11)
We need to find solution for jvm 17.

```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @77b52d12
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at net.openhft.compiler.CompilerUtils.<clinit>(CompilerUtils.java:65)
```
Internal packages that will no longer be open by default: https://cr.openjdk.org/~mr/jigsaw/jdk8-packages-denied-by-default

**Comment by yurem** [comment]
With options `--add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/com.sun=ALL-UNNAMED --add-opens java.base/com.sun.tools.javac.file=ALL-UNNAMED --illegal-access=permit` it also fails.

We need to find JDK17 solution because in future versions `--add-opens` developers can deprecate at all.
