### ISSUE TITLE
fix(jans-setup): "password authentication failed for user jans" while jans installation

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#6143]
**Describe the bug**

**To Reproduce**
1. install jans 1.0.19.nightly with mysql db
2. uninstall jans and remove mysql db and 
3. install jans with pgsq DB
4.  See error
```
FATAL: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "jans"
connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "jans"

(Background on this error at: http://sqlalche.me/e/13/e3q8)
Process rdbm-server: Importing ldif files to pgsql
FATAL: True
Traceback (most recent call last):
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/pool/impl.py", line 139, in _do_get
    with util.safe_reraise():
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/pool/base.py", line 660, in __connect
    with util.safe_reraise():
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "jans"
connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "jans"
```

**Expected behavior**
should not get any error

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/7e007603-4bce-4e4a-9380-e0a32857b150)

**Desktop (please complete the following information):**
  - OS: ubuntu22
  - Version 22
  - DB pgsql
  - jans 1.0.19.nightly

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
@manojs1978 I were not be able to replicate. Most probably you installed jans with pgsql and you forget to remove pgsql completely. This is how you can remove pgsql:

```
apt-get -y --purge remove postgresql
apt-get -y --purge postgresql*
apt-get -y --purge remove postgresql postgresql-doc postgresql-common
rm -r -f /var/log/postgresql
rm -r -f /var/lib/postgresql
rm -r -f /etc/postgresql

```

![image](https://github.com/JanssenProject/jans/assets/6398752/8859f141-3604-4a95-bbb7-824a04bb0f3a)
