### ISSUE TITLE
fix(jans-cli-tui): unable to load

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#6408]
created zipapp from source or download it from the nightly build and try running :

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/mo/Downloads/test/jans-main/jans-cli-tui/./jans-cli-tui.pyz/__main__.py", line 3, in <module>
  File "/home/mo/Downloads/test/jans-main/jans-cli-tui/./jans-cli-tui.pyz/_bootstrap/__init__.py", line 253, in bootstrap
  File "/home/mo/Downloads/test/jans-main/jans-cli-tui/./jans-cli-tui.pyz/_bootstrap/__init__.py", line 59, in import_string
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mo/.shiv/jans-cli-tui.pyz_b16f300f8ccc8c6911924a9509f8af3f21ae59fe9a4d57103982e77cfc937b31/site-packages/cli_tui/jans_cli_tui.py", line 32, in <module>
    from cli import config_cli
  File "/home/mo/.shiv/jans-cli-tui.pyz_b16f300f8ccc8c6911924a9509f8af3f21ae59fe9a4d57103982e77cfc937b31/site-packages/cli_tui/cli/config_cli.py", line 143, in <module>
    op_list = read_swagger(my_op_mode)
  File "/home/mo/.shiv/jans-cli-tui.pyz_b16f300f8ccc8c6911924a9509f8af3f21ae59fe9a4d57103982e77cfc937b31/site-packages/cli_tui/cli/config_cli.py", line 130, in read_swagger
    config_ = ruamel.yaml.load(f.read().replace('\t', ''), ruamel.yaml.RoundTripLoader)
  File "/home/mo/.shiv/jans-cli-tui.pyz_b16f300f8ccc8c6911924a9509f8af3f21ae59fe9a4d57103982e77cfc937b31/site-packages/ruamel/yaml/main.py", line 1071, in load
    error_deprecation('load', 'load', arg=_error_dep_arg, comment=_error_dep_comment)
  File "/home/mo/.shiv/jans-cli-tui.pyz_b16f300f8ccc8c6911924a9509f8af3f21ae59fe9a4d57103982e77cfc937b31/site-packages/ruamel/yaml/main.py", line 1025, in error_deprecation
    raise AttributeError(s, name=None)
AttributeError: 
"load()" has been removed, use

  yaml = YAML(typ='rt')
  yaml.load(...)

and register any classes that you use, or check the tag attribute on the loaded data,
instead of file "/home/mo/.shiv/jans-cli-tui.pyz_b16f300f8ccc8c6911924a9509f8af3f21ae59fe9a4d57103982e77cfc937b31/site-packages/cli_tui/cli/config_cli.py", line 130

            config_ = ruamel.yaml.load(f.read().replace('\t', ''), ruamel.yaml.RoundTripLoader)

**Comment by devrimyatar** [comment]
This is due to change in ruamel.yaml library.
