### ISSUE TITLE
fix(jans-casa): error while enrolling OTP

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#6537]
![Clipboard - November 9, 2023 10_55 AM](https://github.com/JanssenProject/jans/assets/5444180/1462fdf4-7548-46f0-aa0b-0d9811345ecf)

```
"java.lang.IllegalStateException: The 'issuer' and label issuer prefix values are different!
	at com.google.common.base.Preconditions.checkState(Preconditions.java:512) ~[guava-32.1.1-jre.jar:?]
	at com.lochbridge.oath.otp.keyprovisioning.OTPAuthURIBuilder.build(OTPAuthURIBuilder.java:425) ~[oath-otp-keyprovisioning-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at io.jans.casa.plugins.authnmethod.service.otp.TOTPAlgorithmService.generateSecretKeyUri(TOTPAlgorithmService.java:58) ~[classes/:?]
	at io.jans.casa.plugins.authnmethod.service.otp.TOTPAlgorithmService$Proxy$_$$_WeldClientProxy.generateSecretKeyUri(Unknown Source) ~[classes/:?]
	at io.jans.casa.ui.vm.user.OTPViewModel.showQR(OTPViewModel.java:164) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.zkoss.bind.impl.ParamCall.call(ParamCall.java:174) ~[zkbind-9.6.0.2-jakarta.jar:9.6.0.2-migrated-1.0.0]
	at org.zkoss.bind.impl.BinderImpl.handleNotifyChange(BinderImpl.java:1952) ~[zkbind-9.6.0.2-jakarta.jar:9.6.0.2-migrated-1.0.0]
	at org.zkoss.bind.impl.BinderImpl.doExecute(BinderImpl.java:2131) ~[zkbind-9.6.0.2-jakarta.jar:9.6.0.2-migrated-1.0.0]
	at org.zkoss.bind.impl.BinderImpl.doCommand(BinderImpl.java:1847) ~[zkbind-9.6.0.2-jakarta.jar:9.6.0.2-migrated-1.0.0]
...
```

https://github.com/GluuFederation/private/blob/a490cb891d3f87de583851bdd8b67c55aef1f5c7/infrastructure/gluu-configuration/scripts.tf#L136

**Comment by jgomer2001** [comment]
I suspect it is caused by casa using the uid having special chars

**Comment by jgomer2001** [comment]
Only the colon character turned out to be problematic
