### ISSUE TITLE
fix(jans-config-api): getting pgsql exception after device auth verfication

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#6870]
**Describe the bug**
 getting pgsql exception after device auth verfication

**To Reproduce**
1. install jans 1.0.21.nightly
2. complete device auth
3.  See error

**Expected behavior**
should not get any error after devic auth

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/c0fe4873-bfa8-42c9-b860-61c114a358d5)

**Desktop (please complete the following information):**
  - OS: suse
-Jans 1.0.21.nighlty
-DB pgsql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pujavs** [comment]
@yurem i am getting error from ORM for the query to fetch scripts from PgSQL DB.
Attached is the logs, refer line#1092 onwards
**Caused by:
Failed to build search entries query. Key: 'scripts', expression: '(lower(doc.description) like %% || lower(doc.displayName) like %%) && doc.jansEnabled = true'**
[Issue#6870_jans-config-api_logs.log](https://github.com/JanssenProject/jans/files/13523362/Issue.6870_jans-config-api_logs.log)

Request you advice.

**Comment by yurem** [comment]
Fixed

**Comment by moabu** [comment]
@yurem I think this is related 

```
java.lang.IllegalArgumentException: No enum constant java.sql.JDBCType.DATETIME
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
	at java.sql.JDBCType.valueOf(JDBCType.java:34) ~[java.sql:?]
	at io.jans.orm.sql.impl.SqlFilterConverter.prepareTypedExpressionValue(SqlFilterConverter.java:505) ~[jans-orm-sql-1.0.21-SNAPSHOT.jar:?]
	at io.jans.orm.sql.impl.SqlFilterConverter.buildTypedExpression(SqlFilterConverter.java:452) ~[jans-orm-sql-1.0.21-SNAPSHOT.jar:?]
	at io.jans.orm.sql.impl.SqlFilterConverter.convertToSqlFilterImpl(SqlFilterConverter.java:231) ~[jans-orm-sql-1.0.21-SNAPSHOT.jar:?]
	at io.jans.orm.sql.impl.SqlFilterConverter.convertToSqlFilterImpl(SqlFilterConverter.java:120) ~[jans-orm-sql-1.0.21-SNAPSHOT.jar:?]
	at io.jans.orm.sql.impl.SqlFilterConverter.convertToSqlFilter(SqlFilterConverter.java:86) ~[jans-orm-sql-1.0.21-SNAPSHOT.jar:?]
	at io.jans.orm.sql.impl.SqlFilterConverter.convertToSqlFilter(SqlFilterConverter.java:81) ~[jans-orm-sql-1.0.21-SNAPSHOT.jar:?]
	at io.jans.orm.sql.impl.SqlFilterConverter.convertToSqlFilter(SqlFilterConverter.java:77) ~[jans-orm-sql-1.0.21-SNAPSHOT.jar:?]
	at io.jans.orm.sql.impl.SqlEntryManager.toSqlFilter(SqlEntryManager.java:808) ~[jans-orm-sql-1.0.21-SNAPSHOT.jar:?]
	at io.jans.orm.sql.impl.SqlEntryManager.findEntriesImpl(SqlEntryManager.java:478) ~[jans-orm-sql-1.0.21-SNAPSHOT.jar:?]
	at io.jans.orm.sql.impl.SqlEntryManager.findEntries(SqlEntryManager.java:393) ~[jans-orm-sql-1.0.21-SNAPSHOT.jar:?]
	at io.jans.orm.impl.BaseEntryManager.findEntries(BaseEntryManager.java:153) ~[jans-orm-core-1.0.21-SNAPSHOT.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor122.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at io.jans.orm.PersistenceEntryManager$EntityManager$2057902728$Proxy$_$$_WeldClientProxy.findEntries(Unknown Source) ~[jans-orm-core-1.0.21-SNAPSHOT.jar:?]
	at io.jans.as.server.service.ciba.CibaRequestService.loadExpiredByStatus(CibaRequestService.java:105) ~[classes/:?]
	at io.jans.as.server.service.ciba.CibaRequestsProcessorJob.processImpl(CibaRequestsProcessorJob.java:135) ~[classes/:?]
	at io.jans.as.server.service.ciba.CibaRequestsProcessorJob$Proxy$_$$_WeldSubclass.processImpl(Unknown Source) ~[classes/:?]
	at io.jans.as.server.service.ciba.CibaRequestsProcessorJob.process(CibaRequestsProcessorJob.java:100) ~[classes/:?]
	at io.jans.as.server.service.ciba.CibaRequestsProcessorJob$Proxy$_$$_WeldSubclass.process$$super(Unknown Source) ~[classes/:?]
	at jdk.internal.reflect.GeneratedMethodAccessor120.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at io.jans.service.cdi.async.AsynchronousInterceptor$1.get(AsynchronousInterceptor.java:42) ~[jans-core-service-1.0.21-SNAPSHOT.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]"

**Comment by yurem** [comment]
No, this this stack trace should not led to any erorrs
It just mean that in JDBC enum list of types is not conform DB rtypes
I will comment out this message again

**Comment by pujavs** [comment]
assigning to @manojs1978 for verification as @yurem confirmed fix
