### ISSUE TITLE
fix(config-api): logging service issue on startup 

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#6944]
On `config-api` startup getting LogService issue

**Error snippet:**
05-12 08:42:00.540 ERROR [main] jans.service.logger.LoggerService LoggerService.java:133- Exception happened while updating logger configuration after base configuration update
org.jboss.weld.exceptions.IllegalProductException: WELD-000052: Cannot return null from a non-dependent producer method: Producer for Producer Method [ApiAppConfiguration] with qualifiers [@Any @Default] declared as [[BackedAnnotatedMethod] @Produces @ApplicationScoped public io.jans.configapi.configuration.ConfigurationFactory.getApiAppConfiguration()] declared on Managed Bean [class io.jans.configapi.configuration.ConfigurationFactory] with qualifiers [@Any @Default]
	at io.jans.configapi.configuration.ConfigurationFactory.getApiAppConfiguration(ConfigurationFactory.java:0)
  StackTrace:
	at org.jboss.weld.bean.AbstractProducerBean.checkReturnValue(AbstractProducerBean.java:136) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.bean.AbstractProducerBean.create(AbstractProducerBean.java:181) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:96) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:140) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:102) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:131) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at io.jans.configapi.model.configuration.ApiAppConfiguration$Proxy$_$$_WeldClientProxy.getDisableJdkLogger(Unknown Source) ~[jans-config-api-common-1.0.21-SNAPSHOT.jar:?]
	at io.jans.configapi.service.logger.LoggerService.isDisableJdkLogger(LoggerService.java:16) ~[classes/:?]
	at io.jans.configapi.service.logger.LoggerService$Proxy$_$$_WeldSubclass.isDisableJdkLogger(Unknown Source) ~[classes/:?]
	at io.jans.service.logger.LoggerService.setDisableJdkLogger(LoggerService.java:168) ~[jans-core-service-1.0.21-SNAPSHOT.jar:?]
	at io.jans.service.logger.LoggerService.updateLoggerSeverityImpl(LoggerService.java:145) ~[jans-core-service-1.0.21-SNAPSHOT.jar:?]
	at io.jans.service.logger.LoggerService.updateLoggerSeverity(LoggerService.java:131) ~[jans-core-service-1.0.21-SNAPSHOT.jar:?]
	at io.jans.configapi.service.logger.LoggerService$Proxy$_$$_WeldSubclass.updateLoggerSeverity(Unknown Source) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:168) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at jakarta.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:125) ~[jakarta.enterprise.cdi-api-3.0.0.jar:?]
	at org.jboss.weld.util.Observers.notify(Observers.java:166) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:96) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at io.jans.configapi.plugin.saml.configuration.SamlConfigurationFactory.loadSamlConfigFromDb(SamlConfigurationFactory.java:192) ~[kc-saml-plugin.jar:?]
	at io.jans.configapi.plugin.saml.configuration.SamlConfigurationFactory.create(SamlConfigurationFactory.java:137) ~[kc-saml-plugin.jar:?]
	at io.jans.configapi.plugin.saml.configuration.SamlConfigurationFactory$Proxy$_$$_WeldSubclass.create(Unknown Source) ~[kc-saml-plugin.jar:?]
	at io.jans.configapi.plugin.saml.configuration.SamlConfigurationFactory$Proxy$_$$_WeldClientProxy.create(Unknown Source) ~[kc-saml-plugin.jar:?]
	at io.jans.configapi.plugin.saml.configuration.SamlAppInitializer.onAppStart(SamlAppInitializer.java:57) ~[kc-saml-plugin.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:168) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at jakarta.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:125) ~[jakarta.enterprise.cdi-api-3.0.0.jar:?]
	at org.jboss.weld.util.Observers.notify(Observers.java:166) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.bootstrap.BeanDeploymentModule.fireEvent(BeanDeploymentModule.java:93) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.module.web.servlet.HttpContextLifecycle.fireEventForApplicationScope(HttpContextLifecycle.java:161) ~[weld-web-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.module.web.servlet.HttpContextLifecycle.contextInitialized(HttpContextLifecycle.java:147) ~[weld-web-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.module.web.servlet.WeldInitialListener.contextInitialized(WeldInitialListener.java:99) ~[weld-web-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.servlet.api.helpers.ForwardingServletListener.contextInitialized(ForwardingServletListener.java:34) ~[weld-spi-4.0.SP1.jar:4.0.0.SP1]
	at org.jboss.weld.environment.servlet.EnhancedListener.onStartup(EnhancedListener.java:66) ~[weld-servlet-core-4.0.3.Final.jar:4.0.3.Final]
	at org.eclipse.jetty.servlet.ServletContainerInitializerHolder.doStart(ServletContainerInitializerHolder.java:148) ~[jetty-servlet-11.0.15.jar:11.0.15]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[?:?]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171) ~[?:?]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) ~[?:?]
	at org.eclipse.jetty.servlet.ServletContextHandler$ServletContainerInitializerStarter.doStart(ServletContextHandler.java:1660) ~[jetty-servlet-11.0.15.jar:11.0.15]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[?:?]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:369) ~[jetty-servlet-11.0.15.jar:11.0.15]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1305) ~[?:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:902) ~[jetty-server-11.0.15.jar:11.0.15]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:306) ~[jetty-servlet-11.0.15.jar:11.0.15]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:533) ~[?:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[?:?]
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:40) ~[?:?]
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:183) ~[?:?]
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:516) ~[?:?]
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:151) ~[?:?]
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:186) ~[?:?]
	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:462) ~[?:?]
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:58) ~[?:?]
	at org.eclipse.jetty.util.Scanner$DiscreteListener.pathAdded(Scanner.java:282) ~[?:?]
	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:836) ~[?:?]
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:802) ~[?:?]
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:709) ~[?:?]
	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:597) ~[?:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[?:?]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171) ~[?:?]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121) ~[?:?]
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:158) ~[?:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[?:?]
	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:605) ~[?:?]
	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:246) ~[?:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[?:?]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171) ~[?:?]
	at org.eclipse.jetty.server.Server.start(Server.java:470) ~[?:?]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121) ~[?:?]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89) ~[?:?]
	at org.eclipse.jetty.server.Server.doStart(Server.java:415) ~[?:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[?:?]
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1875) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:229) ~[?:?]
	at org.eclipse.jetty.start.Main.start(Main.java:528) ~[?:?]
	at org.eclipse.jetty.start.Main.main(Main.java:76) ~[?:?]

**Log Error:**
[devrimyatar - Tue Dec 05 2023 12_25_44 GMT+0300 (GMT+03_00).txt](https://github.com/JanssenProject/jans/files/13559459/devrimyatar.-.Tue.Dec.05.2023.12_25_44.GMT%2B0300.GMT%2B03_00.txt)

**Comment by pujavs** [comment]
Fixed via PR [7054](https://github.com/JanssenProject/jans/pull/7054)
