### ISSUE TITLE
fix(agama): re-engineer how calls are working in the engine

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#7064]
Case 1. Suppose

```
map = Call java.util.Collections#emptyMap
Call map size
```

it fails miserably with:

```
Caused by: java.lang.IllegalAccessException: class io.jans.agama.engine.service.ActionService cannot access a member of class java.util.Collections$EmptyMap (in module java.base) with modifiers "public"
	at jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:560) ~[?:?]
	at io.jans.agama.engine.service.ActionService.callAction(ActionService.java:146) ~[agama-engine-1.0.21-SNAPSHOT.jar:?]
```

This is because the class returned is a sort of inner class (`java.util.Collections$EmptyMap`) and its `size` method is not accessible by external code - the method enforces access control despite it's public

Same issues occur when trying to Call methods on objects returned by Calls like `java.util.Map#of ...`  and similar

-----------------------------

Case 2. Suppose

```
package co;

public class SubTest extends Test {
    ...
}

...

package co;

public class Test {

    private String id;

    public String getId() {
        return id;
    }
    ....
}
```

and

```
obj = Call co.SubTest#new
Call obj getId
```

It fails with `NoSuchMethodException: Unable to find a method called getId with arity 0 in class co.SubTest` 

The implementation is not scanning methods in the parent class

**Comment by jgomer2001** [comment]
Case 3. A call like

```
Call one.two.three#new
```

Crahes with `InvocationTargetException` if the  underlying constructor throws an exception. It should throw the original exception without wrapping it

**Comment by jgomer2001** [comment]
case 4. A call like

```
Call p method param
```

where `p` is an unknown (unset) variable in the flow, degenerates in attempts to lookup `method` on the `String` class. 

This seems to be that way because an instance of `org.mozilla.javascript.Undefined` is received, and the `getClass` method on it seems to give String.

**Comment by jgomer2001** [comment]
case 5. A call like

```
s = "a string"
Call instance method s
```

where `method` has param of type `char[]` or `Character[]`  fails. The conversion is only succeeding when the param is exactly `CharSequence`, `String` or `char`
