### ISSUE TITLE
BUG: newly added EDDSA cause exception

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#721]
**Describe the bug**

```
2022-01-27 13:38:04,822 ERROR [main]  [jans.as.server.model.config.ConfigurationFactory] (ConfigurationFactory.java:458) - Failed to convert json value '%d [%thread] %-5level %logger - %msg%n java.lang.IllegalArgumentException: Unknown signature type requested: EDDSA
    at org.bouncycastle.operator.DefaultSignatureAlgorithmIdentifierFinder.generate(Unknown Source) ~[jans-auth-client-jar-with-dependencies.jar:?]
    at org.bouncycastle.operator.DefaultSignatureAlgorithmIdentifierFinder.find(Unknown Source) ~[jans-auth-client-jar-with-dependencies.jar:?]
    at org.bouncycastle.operator.jcajce.JcaContentSignerBuilder.&lt;init&gt;(Unknown Source) ~[jans-auth-client-jar-with-dependencies.jar:?]
    at io.jans.as.model.crypto.AuthCryptoProvider.generateV3Certificate(AuthCryptoProvider.java:393) ~[jans-auth-client-jar-with-dependencies.jar:?]
    at io.jans.as.model.crypto.AuthCryptoProvider.getJson(AuthCryptoProvider.java:517) ~[jans-auth-client-jar-with-dependencies.jar:?]
    at io.jans.as.model.crypto.AuthCryptoProvider.generateKeySignature(AuthCryptoProvider.java:473) ~[jans-auth-client-jar-with-dependencies.jar:?]
    at io.jans.as.model.crypto.AuthCryptoProvider.generateKey(AuthCryptoProvider.java:173) ~[jans-auth-client-jar-with-dependencies.jar:?]
    at io.jans.as.client.util.KeyGenerator$Cli.generateKeys(KeyGenerator.java:207) ~[jans-auth-client-jar-with-dependencies.jar:?]
    at io.jans.as.client.util.KeyGenerator$Cli.parse(KeyGenerator.java:178) [jans-auth-client-jar-with-dependencies.jar:?]
    at io.jans.as.client.util.KeyGenerator.main(KeyGenerator.java:89) [jans-auth-client-jar-with-dependencies.jar:?]
usage: KeyGenerator -sig_keys alg ... -enc_keys alg ... -expiration n_days
```

**Comment by yuriyz** [comment]
https://github.com/JanssenProject/jans/pull/670

**Comment by yuriyz** [comment]
Fixed in https://github.com/JanssenProject/jans/pull/727
