### ISSUE TITLE
BUG: NPE in JARM

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#728]
**Describe the bug**
```
java.lang.NullPointerException: null
	at io.jans.as.server.authorize.ws.rs.AuthorizeRestWebServiceImpl.fillRedirectUriResponseforJARM(AuthorizeRestWebServiceImpl.java:791) ~[classes/:?]
	at io.jans.as.server.authorize.ws.rs.AuthorizeRestWebServiceImpl.requestAuthorization(AuthorizeRestWebServiceImpl.java:423) ~[classes/:?]
	at io.jans.as.server.authorize.ws.rs.AuthorizeRestWebServiceImpl.requestAuthorizationGet(AuthorizeRestWebServiceImpl.java:192) ~[classes/:?]
	at io.jans.as.server.authorize.ws.rs.AuthorizeRestWebServiceImpl$Proxy$_$$_WeldClientProxy.requestAuthorizationGet(Unknown Source) ~[classes/:?]
```

**Comment by yuriyz** [comment]
Fixed
