### ISSUE TITLE
fix(jans-auth-server): avoid NPE if `UpdateToken` script returned `False`

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#7342]
### Description

If `UpdateToken` script returned `False` AT is not created which is correct but we see also NPE in logs. We should avoid NPE and process it cleanly.

```
 java.lang.NullPointerException: Cannot invoke "io.jans.as.server.model.common.AccessToken.getTokenType()" because "accessToken" is null
	at io.jans.as.server.token.ws.rs.TokenRestWebServiceImpl.processClientGredentials(TokenRestWebServiceImpl.java:314) ~[classes/:?]
	at io.jans.as.server.token.ws.rs.TokenRestWebServiceImpl.requestAccessToken(TokenRestWebServiceImpl.java:201) ~[classes/:?]
	at io.jans.as.server.token.ws.rs.TokenRestWebServiceImpl$Proxy$_$$_WeldClientProxy.requestAccessToken(Unknown Source) ~[classes/:?]
```

**Comment by yuriyz** [comment]
Also `processClientGredentials` has typo it must be `processClientCredentials`
