### ISSUE TITLE
fix: CN upgrade from 1.0.21 to 1.0.22 and 1.0.22 install faliure

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#7414]
```
Traceback (most recent call last):
  File "/app/jans_aio/jans_casa/upgrade.py", line 316, in <module>
    main()
  File "/app/jans_aio/jans_casa/upgrade.py", line 312, in main
    upgrade.invoke()
  File "/app/jans_aio/jans_casa/upgrade.py", line 174, in invoke
    self.update_client_uris()
  File "/app/jans_aio/jans_casa/upgrade.py", line 287, in update_client_uris
    client_uris = entry.attrs[key]["v"] 
    ```
    
    ```
     Traceback (most recent call last):
  File "/app/jans_aio/jans_casa/upgrade.py", line 316, in <module>
  ```

**Comment by iromli** [comment]
The issue caused by data type change in `jansClnt.jansPostLogoutRedirectURI` column defined in upstream. I will ask team about this change.
