### ISSUE TITLE
fix(jans-auth-server): handle ssa validation error

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#7454]
When SSA are allowed to be used in DCR or used in other manners the returned response to an invalidated or outdated SSA should not be an unknown code 422 as it is currently. This leads to loaded logs and also an unknown response to the client which  doesn't indicate anything regarding the SSAs status. 

```
auth - 2024-01-22 08:31:06,136 ERROR [qtp937277082-127] [server.ssa.ws.rs.action.SsaValidateAction] (SsaValidateAction.java:73) - HTTP 422 Unknown Code
jakarta.ws.rs.WebApplicationException: HTTP 422 Unknown Code
	at io.jans.as.server.ssa.ws.rs.SsaRestWebServiceValidator.getValidSsaByJti(SsaRestWebServiceValidator.java:117) ~[classes/:?]
	at io.jans.as.server.ssa.ws.rs.action.SsaValidateAction.validate(SsaValidateAction.java:64) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:190) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:208) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.PyObject.__call__(PyObject.java:477) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.PyObject.__call__(PyObject.java:481) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.PyMethod.__call__(PyMethod.java:141) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.pycode._pyx16.validateSSA$10(scan_client_registration.py:146) ~[?:?]
	at org.python.pycode._pyx16.call_function(scan_client_registration.py) ~[?:?]
	at org.python.core.PyTableCode.call(PyTableCode.java:173) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:150) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.PyFunction.__call__(PyFunction.java:426) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.PyMethod.__call__(PyMethod.java:141) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.pycode._pyx16.createClient$5(scan_client_registration.py:119) ~[?:?]
	at org.python.pycode._pyx16.call_function(scan_client_registration.py) ~[?:?]
	at org.python.core.PyTableCode.call(PyTableCode.java:173) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:306) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:197) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.PyFunction.__call__(PyFunction.java:485) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.PyMethod.__call__(PyMethod.java:228) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.PyMethod.__call__(PyMethod.java:218) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.PyMethod.__call__(PyMethod.java:213) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.PyObject._jcallexc(PyObject.java:3565) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.PyObject._jcall(PyObject.java:3598) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.proxies.__main__$ClientRegistration$18.createClient(Unknown Source) ~[?:?]
	at io.jans.as.server.service.external.ExternalDynamicClientRegistrationService.executeExternalCreateClientMethod(ExternalDynamicClientRegistrationService.java:68) ~[classes/:?]
	at io.jans.as.server.service.external.ExternalDynamicClientRegistrationService.executeExternalCreateClientMethods(ExternalDynamicClientRegistrationService.java:85) ~[classes/:?]
	at io.jans.as.server.service.external.ExternalDynamicClientRegistrationService$Proxy$_$$_WeldClientProxy.executeExternalCreateClientMethods(Unknown Source) ~[classes/:?]
	at io.jans.as.server.register.ws.rs.action.RegisterCreateAction.executeDynamicScrypt(RegisterCreateAction.java:213) ~[classes/:?]
	at io.jans.as.server.register.ws.rs.action.RegisterCreateAction.createClient(RegisterCreateAction.java:163) ~[classes/:?]
	at io.jans.as.server.register.ws.rs.RegisterRestWebServiceImpl.requestRegister(RegisterRestWebServiceImpl.java:52) ~[classes/:?]
	at io.jans.as.server.register.ws.rs.RegisterRestWebServiceImpl$Proxy$_$$_WeldClientProxy.requestRegister(Unknown Source) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170) ~[resteasy-core-6.0.3.Final.jar:6.0.3.Final]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130) ~[resteasy-core-6.0.3.Final.jar:6.0.3.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660) ~[resteasy-core-6.0.3.Final.jar:6.0.3.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524) ~[resteasy-core-6.0.3.Final.jar:6.0.3.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474) ~[resteasy-core-6.0.3.Final.jar:6.0.3.Final]
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364) ~[resteasy-core-6.0.3.Final.jar:6.0.3.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476) ~[resteasy-core-6.0.3.Final.jar:6.0.3.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434) ~[resteasy-core-6.0.3.Final.jar:6.0.3.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408) ~[resteasy-core-6.0.3.Final.jar:6.0.3.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69) ~[resteasy-core-6.0.3.Final.jar:6.0.3.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492) ~[resteasy-core-6.0.3.Final.jar:6.0.3.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261) ~[resteasy-core-6.0.3.Final.jar:6.0.3.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161) ~[resteasy-core-6.0.3.Final.jar:6.0.3.Final]
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364) ~[resteasy-core-6.0.3.Final.jar:6.0.3.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164) ~[resteasy-core-6.0.3.Final.jar:6.0.3.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247) ~[resteasy-core-6.0.3.Final.jar:6.0.3.Final]
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249) ~[resteasy-core-6.0.3.Final.jar:6.0.3.Final]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:60) ~[resteasy-core-6.0.3.Final.jar:6.0.3.Final]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55) ~[resteasy-core-6.0.3.Final.jar:6.0.3.Final]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587) ~[jetty-jakarta-servlet-api-5.0.2.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665) ~[?:?]
	at io.jans.as.server.auth.AuthenticationFilter.doFilter(AuthenticationFilter.java:247) ~[classes/:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[?:?]
	at io.jans.as.server.audit.debug.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:69) ~[classes/:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:210) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[?:?]
	at io.jans.server.filters.AbstractCorsFilter.handleNonCORS(AbstractCorsFilter.java:357) ~[jans-core-server-1.0.22-SNAPSHOT.jar:?]
	at io.jans.server.filters.AbstractCorsFilter.doFilter(AbstractCorsFilter.java:123) ~[jans-core-server-1.0.22-SNAPSHOT.jar:?]
	at io.jans.as.server.filter.CorsFilter.doFilter(CorsFilter.java:116) ~[classes/:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[?:?]
	at io.jans.as.server.filter.CorrelationIdFilter.doFilter(CorrelationIdFilter.java:49) ~[classes/:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[?:?]
	at org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:170) ~[websocket-servlet-11.0.16.jar:11.0.16]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527) ~[?:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131) ~[?:?]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578) ~[?:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[?:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223) ~[?:?]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570) ~[?:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[?:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381) ~[?:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484) ~[?:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543) ~[?:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) ~[?:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303) ~[?:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) ~[?:?]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:192) ~[?:?]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51) ~[?:?]
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173) ~[?:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[?:?]
	at org.eclipse.jetty.server.Server.handle(Server.java:563) ~[?:?]
	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598) ~[?:?]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753) ~[?:?]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501) ~[?:?]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282) ~[?:?]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314) ~[?:?]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[?:?]
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199) ~[?:?]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411) ~[?:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969) ~[?:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194) ~[?:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Perhaps we are better off with responding with a 403

**Comment by Milton-Ch** [comment]
@moabu 
Work was done according to this documentation https://gluu-arpine.stoplight.io/docs/ssa-1/branches/main/2d1658a3842b3-validate-ssa.
But we can change it to 403, @yuriz, what do you think?

**Comment by yuriyz** [comment]
Usually AS is throwing 400 Bad Request with error and description. 
Spec example:
https://openid.net/specs/openid-connect-registration-1_0.html#RegistrationError

Thus I propose to return 400 with usual json body
```
HTTP/1.1 400 Bad Request
Content-Type: application/json
Cache-Control: no-store

{
   "error": "invalid_jti",
   "error_description": "jti value is not invalid"
}
```

**Comment by Milton-Ch** [comment]
Ok, I will proceed to implement it

**Comment by Milton-Ch** [comment]
@yuriyz @moabu 

There is a problem to return in the `response body`.
The method is a `HEAD`, and according to the `HTTP protocol`, HEADs do not return values in the `response body`.

**Comment by yuriyz** [comment]
It can be simple POST with `/validate-ssa` to not clash with create ssa.

**Comment by Milton-Ch** [comment]
@yuriyz 

Wouldn't it be convenient to maintain the `/ssa` endpoint, to place `/ssa/validation`?

**Comment by yuriyz** [comment]
Yes, why not.

**Comment by Milton-Ch** [comment]
@yuriyz @moabu 

Can you please have a look at the PR

**Comment by yuriyz** [comment]
already did, PR is approved
