### ISSUE TITLE
fix(jans-cli-tui): smtp configuartion test failed

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#7537]
**Describe the bug**
smtp configuartion test failed

**To Reproduce**
1. install jans 1.0.22
2. add smtp configuration details
3. save configuration and test it
5. See error

**Expected behavior**
test should be successful

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/90d3a175-03bb-451b-8f5e-937d429bfdba)

**Desktop (please complete the following information):**
  - OS: suse/ubuntu22
-jans 1.0.22
-DB opendj

**Smartphone (please complete the following information):**

**Additional context**
```
25-01 04:38:39.901 ERROR [qtp1301664418-19] io.jans.service.MailService MailService.java:299- Failed to send message
javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials bx9-20020a05622a090900b0042a460cad28sm2857518qtb.91 - gsmtp

        at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:947) ~[jakarta.mail-1.6.7.jar:1.6.7]
        at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:858) ~[jakarta.mail-1.6.7.jar:1.6.7]
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:762) ~[jakarta.mail-1.6.7.jar:1.6.7]
        at javax.mail.Service.connect(Service.java:364) ~[jakarta.mail-1.6.7.jar:1.6.7]
        at javax.mail.Service.connect(Service.java:222) ~[jakarta.mail-1.6.7.jar:1.6.7]
        at javax.mail.Service.connect(Service.java:171) ~[jakarta.mail-1.6.7.jar:1.6.7]
        at javax.mail.Transport.send0(Transport.java:230) ~[jakarta.mail-1.6.7.jar:1.6.7]
        at javax.mail.Transport.send(Transport.java:100) ~[jakarta.mail-1.6.7.jar:1.6.7]
        at io.jans.service.MailService.sendMail(MailService.java:297) ~[jans-core-service-1.0.22.jar:?]
        at io.jans.service.MailService.sendMailSigned(MailService.java:158) ~[jans-core-service-1.0.22.jar:?]
        at io.jans.service.MailService$Proxy$_$$_WeldClientProxy.sendMailSigned(Unknown Source) ~[jans-core-service-1.0.22.jar:?]
        at io.jans.configapi.rest.resource.auth.ConfigSmtpResource.testSmtpConfiguration(ConfigSmtpResource.java:153) ~[classes/:?]
        at io.jans.configapi.rest.resource.auth.ConfigSmtpResource$Proxy$_$$_WeldSubclass.testSmtpConfiguration$$super(Unknown Source) ~[classes/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
        at org.hibernate.validator.cdi.internal.interceptor.ValidationInterceptor.validateMethodInvocation(ValidationInterceptor.java:79) ~[hibernate-validator-cdi-7.0.5.Final.jar:7.0.5.Final]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
@@@                                          
```

**Comment by manojs1978** [comment]
[config.zip](https://github.com/JanssenProject/jans/files/14046959/config.zip)

**Comment by pujavs** [comment]
@manojs1978 as per the error log there is issue with the credentials.  
I am able to test SMTP with Gmail account. See screenshot below.
I had shared steps with you last time, regarding first creating App password in GMAIL. 
I have now created a Wiki for your reference. https://github.com/JanssenProject/jans/wiki/SMTP-testing-with-GMAIL-account
Please try again and confirm.

![image](https://github.com/JanssenProject/jans/assets/43700552/8f8a0610-6360-4b04-b826-303461871bfe)

**Comment by manojs1978** [comment]
after regenerating app passwd it is working fine
![image](https://github.com/JanssenProject/jans/assets/5729240/05de7dce-ab5b-42a4-a26d-7390202aa74f)
