### ISSUE TITLE
fix(jans-linux-setup): postgres exception thrown during lock client setup

### ISSUE THREAD

**Issue by SafinWasi** [JanssenProject/jans#7688]
**Describe the bug**
When a lock client is configured with a remote postgresql server with existing Jans installation, the installer throws an exception.

**To Reproduce**
1. On one machine, install Jans with lock configured as a service and postgres as the local persistence
2. On another machine, install only lock components and remote postgres, with the database being that of the first machine
3. The installer throws an exception, with stack trace noted below

**Additional context**
```
...
Proceed with these values [Y|n] Y
FATAL: True
Traceback (most recent call last):
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/jans/jans-setup/setup.py", line 432, in do_installation
    jansAuthInstaller.start_installation()
  File "/opt/jans/jans-setup/setup_app/installers/base.py", line 46, in start_installation
    self.render_import_templates()
  File "/opt/jans/jans-setup/setup_app/installers/jans_auth.py", line 149, in render_import_templates
    self.dbUtils.import_ldif([self.ldif_config, self.ldif_scripts, self.ldif_role_scope_mappings, self.ldif_people, self.ldif_groups])
  File "/opt/jans/jans-setup/setup_app/utils/db_utils.py", line 918, in import_ldif
    if self.dn_exists_rdbm(dn, table_name):
  File "/opt/jans/jans-setup/setup_app/utils/db_utils.py", line 381, in dn_exists_rdbm
    return self.session.query(sqlalchemy_table).filter(sqlalchemy_table.columns.dn == dn).first()
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/orm/query.py", line 3429, in first
    ret = list(self[0:1])
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/orm/query.py", line 3203, in __getitem__
    return list(res)
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/opt/jans/jans-setup/setup_app/pylib/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.InFailedSqlTransaction) current transaction is aborted, commands ignored until end of transaction block

[SQL: SELECT "jansAppConf".doc_id AS "jansAppConf_doc_id", "jansAppConf"."objectClass" AS "jansAppConf_objectClass", "jansAppConf".dn AS "jansAppConf_dn", "jansAppConf".c AS "jansAppConf_c", "jansAppConf".ou AS "jansAppConf_ou", "jansAppConf".description AS "jansAppConf_description", "jansAppConf"."displayName" AS "jansAppConf_displayName", "jansAppConf"."jansHostname" AS "jansAppConf_jansHostname", "jansAppConf"."jansLastUpd" AS "jansAppConf_jansLastUpd", "jansAppConf"."jansManager" AS "jansAppConf_jansManager", "jansAppConf"."jansOrgProfileMgt" AS "jansAppConf_jansOrgProfileMgt", "jansAppConf"."jansScimEnabled" AS "jansAppConf_jansScimEnabled", "jansAppConf"."jansEmail" AS "jansAppConf_jansEmail", "jansAppConf"."jansSmtpConf" AS "jansAppConf_jansSmtpConf", "jansAppConf"."jansSslExpiry" AS "jansAppConf_jansSslExpiry", "jansAppConf"."jansStatus" AS "jansAppConf_jansStatus", "jansAppConf"."jansUrl" AS "jansAppConf_jansUrl", "jansAppConf".inum AS "jansAppConf_inum", "jansAppConf".o AS "jansAppConf_o", "jansAppConf"."jansAuthMode" AS "jansAppConf_jansAuthMode", "jansAppConf"."jansDbAuth" AS "jansAppConf_jansDbAuth", "jansAppConf"."jansLogViewerConfig" AS "jansAppConf_jansLogViewerConfig", "jansAppConf"."jansLogConfigLocation" AS "jansAppConf_jansLogConfigLocation", "jansAppConf"."jansCacheConf" AS "jansAppConf_jansCacheConf", "jansAppConf"."jansMessageConf" AS "jansAppConf_jansMessageConf", "jansAppConf"."jansDocStoreConf" AS "jansAppConf_jansDocStoreConf", "jansAppConf"."jansSoftVer" AS "jansAppConf_jansSoftVer", "jansAppConf"."userPassword" AS "jansAppConf_userPassword", "jansAppConf"."jansConfDyn" AS "jansAppConf_jansConfDyn", "jansAppConf"."jansConfErrors" AS "jansAppConf_jansConfErrors", "jansAppConf"."jansConfStatic" AS "jansAppConf_jansConfStatic", "jansAppConf"."jansConfWebKeys" AS "jansAppConf_jansConfWebKeys", "jansAppConf"."jansWebKeysSettings" AS "jansAppConf_jansWebKeysSettings", "jansAppConf"."jansConfApp" AS "jansAppConf_jansConfApp", "jansAppConf"."jansRevision" AS "jansAppConf_jansRevision"
FROM "jansAppConf"
WHERE "jansAppConf".dn = %(dn_1)s
 LIMIT %(param_1)s]
[parameters: {'dn_1': 'ou=jans-auth,ou=configuration,o=jans', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/13/2j85)
```

**Comment by devrimyatar** [comment]
@SafinWasi Currently, this is not possible. Before any component, setup creates tables, and writes some initial data to db. Thus (2) is not possible.

**Comment by devrimyatar** [comment]
Closing the issue, another issue for jans-lock setup was created https://github.com/JanssenProject/jans/issues/7689
