### ISSUE TITLE
feat(jans-config-api): still return response when password decryption for client fails (due to corruption)

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#7858]
### Description

```
Caused by: io.jans.util.security.StringEncrypter$EncryptionException: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	at io.jans.util.security.StringEncrypter.decrypt(StringEncrypter.java:216) ~[?:?]
	at io.jans.util.security.StringEncrypter.decrypt(StringEncrypter.java:235) ~[?:?]
	at io.jans.util.security.StringEncrypter.decrypt(StringEncrypter.java:229) ~[?:?]
	at io.jans.util.security.StringEncrypter$Proxy$_$$_WeldClientProxy.decrypt(Unknown Source) ~[?:?]
	at io.jans.as.common.service.common.EncryptionService.decrypt(EncryptionService.java:38) ~[?:?]
	at io.jans.as.common.service.common.EncryptionService$Proxy$_$$_WeldClientProxy.decrypt(Unknown Source) ~[?:?]
	at io.jans.configapi.rest.resource.auth.ClientsResource.getClients(ClientsResource.java:299) ~[?:?]
	at io.jans.configapi.rest.resource.auth.ClientsResource.doSearch(ClientsResource.java:325) ~[?:?]
	at io.jans.configapi.rest.resource.auth.ClientsResource.getOpenIdConnectClients(ClientsResource.java:118) ~[?:?]
	at io.jans.configapi.rest.resource.auth.ClientsResource$Proxy$_$$_WeldSubclass.getOpenIdConnectClients$$super(Unknown Source) ~[?:?]
```

Issue occurred here https://github.com/JanssenProject/jans/blob/main/jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/ClientsResource.java#L299

We need to catch exception and print exact client_id for which we are not able to decrypt password. This will help to know exact client with "bad" password. Also we should filter it out and still return result (without decrypted password).

https://support.gluu.org/other/11690/unable-to-start-up-due-to-error-on-the-jwt-in-config-api/#at88506

**Comment by pujavs** [comment]
Implemented change via PR [7814](https://github.com/JanssenProject/jans/pull/7814)
