### ISSUE TITLE
fix(jans-fido2): device enrollment failure on postgresql

### ISSUE THREAD

**Issue by SafinWasi** [JanssenProject/jans#7995]
**Describe the bug**
When enrolling a SuperGluu device via Casa, the enrollment fails with a persistence exception. The app throws a FileNotFound exception at `/jans-fido2/restv1/attestation/registration` and FIDO2 logs are attached below.

EDIT: this behavior is present when enrolling directly via the super_gluu script as well

**To Reproduce**
1. Install Jans and Casa, with postgresql persistence
2. Enable SG script and endpoint
3. Try to enroll an SG device **from Casa**

**Expected behavior**
Casa should be able to enroll devices

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
- Device: Google Pixel 4a
- OS: Android 11
- SuperGluu version: 4.5

**Additional context**
Fido2 log:
```
...
Caused by: io.jans.orm.exception.operation.PersistenceException: Failed to add entry
	at io.jans.orm.sql.operation.impl.SqlOperationServiceImpl.addEntryImpl(SqlOperationServiceImpl.java:213) ~[jans-orm-sql-1.0.23-SNAPSHOT.jar:?]
	at io.jans.orm.sql.operation.impl.SqlOperationServiceImpl.addEntry(SqlOperationServiceImpl.java:177) ~[jans-orm-sql-1.0.23-SNAPSHOT.jar:?]
	at io.jans.orm.sql.impl.SqlEntryManager.persist(SqlEntryManager.java:215) ~[jans-orm-sql-1.0.23-SNAPSHOT.jar:?]
	... 76 more
Caused by: com.querydsl.core.QueryException: Caught PSQLException for insert into "public"."jansFido2RegistrationEntry" ("jansCodeChallenge", "jansCodeChallengeHash", "jansCounter", "creationDate", "del", "exp", "jansId", "jansRegistrationData", "jansStatus", "jansApp", "jansSessStateId", "personInum", "objectClass", "dn", "doc_id")
values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
	at com.querydsl.sql.DefaultSQLExceptionTranslator.translate(DefaultSQLExceptionTranslator.java:50) ~[querydsl-sql-4.4.0.jar:?]
	at com.querydsl.sql.Configuration.translate(Configuration.java:508) ~[querydsl-sql-4.4.0.jar:?]
	at com.querydsl.sql.dml.AbstractSQLInsertClause.execute(AbstractSQLInsertClause.java:437) ~[querydsl-sql-4.4.0.jar:?]
	at io.jans.orm.sql.operation.impl.SqlOperationServiceImpl.addEntryImpl(SqlOperationServiceImpl.java:209) ~[jans-orm-sql-1.0.23-SNAPSHOT.jar:?]
	at io.jans.orm.sql.operation.impl.SqlOperationServiceImpl.addEntry(SqlOperationServiceImpl.java:177) ~[jans-orm-sql-1.0.23-SNAPSHOT.jar:?]
	at io.jans.orm.sql.impl.SqlEntryManager.persist(SqlEntryManager.java:215) ~[jans-orm-sql-1.0.23-SNAPSHOT.jar:?]
	... 76 more
Caused by: org.postgresql.util.PSQLException: ERROR: column "jansCodeChallengeHash" is of type integer but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 278
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:152) ~[postgresql-42.6.0.jar:42.6.0]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136) ~[commons-dbcp2-2.9.0.jar:2.9.0]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136) ~[commons-dbcp2-2.9.0.jar:2.9.0]
	at com.querydsl.sql.dml.AbstractSQLInsertClause.execute(AbstractSQLInsertClause.java:415) ~[querydsl-sql-4.4.0.jar:?]
	at io.jans.orm.sql.operation.impl.SqlOperationServiceImpl.addEntryImpl(SqlOperationServiceImpl.java:209) ~[jans-orm-sql-1.0.23-SNAPSHOT.jar:?]
	at io.jans.orm.sql.operation.impl.SqlOperationServiceImpl.addEntry(SqlOperationServiceImpl.java:177) ~[jans-orm-sql-1.0.23-SNAPSHOT.jar:?]
	at io.jans.orm.sql.impl.SqlEntryManager.persist(SqlEntryManager.java:215) ~[jans-orm-sql-1.0.23-SNAPSHOT.jar:?]
	... 76 more
07-03 17:01:44.606 ERROR [qtp1908143486-14] [io.jans.fido2.model.error.ErrorResponseFactory] (ErrorResponseFactory.java:52) - Exception Handle, status: 500 Internal Server Error, body: {
    "error_description": "Unknown or not found error",
    "error": "unknown_error"
}
```

**Comment by SafinWasi** [comment]
Closed as addressed in https://github.com/JanssenProject/jans/issues/7701
