### ISSUE TITLE
feat(jans-auth-server): don't fail entire request if some of the months in request does not exist (`month=202201 202202 202203`).

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#805]
### Description

Currently if request stat for multiple months and some of the months are not valid (not present in persistence) entire call is failed. We should return empty data in this case and don't fail entire request. Because still other months can be valid and result for them can be returned.

https://admin-ui-test.gluu.org/jans-auth/restv1/internal/stat?month=202201%202202
```
2022-02-11 11:30:00,726 ERROR [qtp1831477404-19] 6bc8afba-d069-46a5-999e-e060dc8503aa [as.server.ws.rs.stat.StatWS] (StatWS.java:239) - Failed to find entries with baseDN: ou=202201,ou=stat,o=jans, filter: (&(&(objectClass=jansStatEntry))(jansId=*))
io.jans.orm.exception.EntryPersistenceException: Failed to find entries with baseDN: ou=202201,ou=stat,o=jans, filter: (&(&(objectClass=jansStatEntry))(jansId=*))
        at io.jans.orm.ldap.impl.LdapEntryManager.findEntries(LdapEntryManager.java:441) ~[jans-orm-ldap-1.0.0-SNAPSHOT.jar:?]
        at io.jans.orm.impl.BaseEntryManager.findEntries(BaseEntryManager.java:158) ~[jans-orm-core-1.0.0-SNAPSHOT.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor227.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
        at io.jans.orm.PersistenceEntryManager$EntityManager$2057902728$Proxy$_$$_WeldClientProxy.findEntries(Unknown Source) ~[jans-orm-core-1.0.0-SNAPSHOT.jar:?]
        at io.jans.as.server.ws.rs.stat.StatWS.buildItem(StatWS.java:225) ~[classes/:?]
        at io.jans.as.server.ws.rs.stat.StatWS.buildResponse(StatWS.java:211) ~[classes/:?]
        at io.jans.as.server.ws.rs.stat.StatWS.stat(StatWS.java:179) ~[classes/:?]
        at io.jans.as.server.ws.rs.stat.StatWS.statGet(StatWS.java:159) ~[classes/:?]
        at io.jans.as.server.ws.rs.stat.StatWS$Proxy$_$$_WeldClientProxy.statGet(Unknown Source) ~[classes/:?]
```

**Comment by yuriyz** [comment]
@duttarnab thank for details.

**Comment by yuriyz** [comment]
It works correctly. `202202 202203` url encoded is `202202%20202203` while UI sent `202202%202203` which indeed fail to recognize `2203`. Also if there is failure to fetch data for given month, it will be skipped from response. Closing this ticket as solved.
