### ISSUE TITLE
fix(jans-keycloak-link): getting error in jans-keycloak-link

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#8203]
**Describe the bug**
getting error in jans-keycloak-link

**To Reproduce**
1. install jans with kc
2. follow steps in document (https://github.com/JanssenProject/jans/blob/main/docs/admin/link/jans-kc-link.md)
3. Create Client on Keycloak
4. Configure Jans Keycloak Link
5. See error in log file

**Expected behavior**
should able to configure jans-keycloak-link

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/79fe1dd5-2519-4da9-babc-a1728847ad01)

**Desktop (please complete the following information):**
  - OS: ubuntu22
-jans 1.1.1.nightly
DB pgsql
**Smartphone (please complete the following information):**

**Additional context**
```
02-04-2024 12:45:03.964 INFO  keycloak.link.timer.JansKeycloakLinkTimer JansKeycloakLinkTimer.java:179- test logger
02-04-2024 12:45:03.964 INFO  keycloak.link.timer.JansKeycloakLinkTimer JansKeycloakLinkTimer.java:209- keycloak server connection check ::
02-04-2024 12:45:03.965 ERROR link.server.service.KeycloakService KeycloakService.java:95- Failed to decrypt string: NHDpvqSZ95D3Z5jZ65kgQvPGeRYAPUGW
io.jans.util.security.StringEncrypter$EncryptionException: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	at io.jans.util.security.StringEncrypter.decrypt(StringEncrypter.java:216) ~[jans-core-util-1.1.1-SNAPSHOT.jar:?]
	at io.jans.util.security.StringEncrypter.decrypt(StringEncrypter.java:235) ~[jans-core-util-1.1.1-SNAPSHOT.jar:?]
	at io.jans.util.security.StringEncrypter.decrypt(StringEncrypter.java:229) ~[jans-core-util-1.1.1-SNAPSHOT.jar:?]
	at io.jans.util.security.StringEncrypter$Proxy$_$$_WeldClientProxy.decrypt(Unknown Source) ~[jans-core-util-1.1.1-SNAPSHOT.jar:?]
	at io.jans.service.EncryptionService.decrypt(EncryptionService.java:39) ~[jans-core-service-1.1.1-SNAPSHOT.jar:?]
	at io.jans.service.EncryptionService$Proxy$_$$_WeldSubclass.decrypt$$super(Unknown Source) ~[jans-core-service-1.1.1-SNAPSHOT.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor51.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.probe.InvocationMonitor$InterceptorAction.proceed(InvocationMonitor.java:199) ~[weld-probe-core-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.probe.InvocationMonitor$InterceptorAction.proceed(InvocationMonitor.java:195) ~[weld-probe-core-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.probe.InvocationMonitor$Action.perform(InvocationMonitor.java:174) ~[weld-probe-core-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.probe.InvocationMonitor.monitor(InvocationMonitor.java:139) ~[weld-probe-core-4.0.3.Final.jar:4.0.3.Final]
	at jdk.internal.reflect.GeneratedMethodAccessor11.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at io.jans.service.EncryptionService$Proxy$_$$_WeldSubclass.decrypt(Unknown Source) ~[jans-core-service-1.1.1-SNAPSHOT.jar:?]
	at io.jans.service.EncryptionService$Proxy$_$$_WeldClientProxy.decrypt(Unknown Source) ~[jans-core-service-1.1.1-SNAPSHOT.jar:?]
	at io.jans.keycloak.link.server.service.KeycloakService.decryptString(KeycloakService.java:93) ~[classes/:?]
	at io.jans.keycloak.link.server.service.KeycloakService$Proxy$_$$_WeldSubclass.decryptString(Unknown Source) ~[classes/:?]
	at io.jans.keycloak.link.server.service.KeycloakService.getKeycloakInstance(KeycloakService.java:40) ~[classes/:?]
	at io.jans.keycloak.link.server.service.KeycloakService$Proxy$_$$_WeldSubclass.getKeycloakInstance$$super(Unknown Source) ~[classes/:?]
	at jdk.internal.reflect.GeneratedMethodAccessor54.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.probe.InvocationMonitor.monitor(InvocationMonitor.java:125) ~[weld-probe-core-4.0.3.Final.jar:4.0.3.Final]
	at jdk.internal.reflect.GeneratedMethodAccessor11.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at io.jans.keycloak.link.server.service.KeycloakService$Proxy$_$$_WeldSubclass.getKeycloakInstance(Unknown Source) ~[classes/:?]
	at io.jans.keycloak.link.server.service.KeycloakService$Proxy$_$$_WeldClientProxy.getKeycloakInstance(Unknown Source) ~[classes/:?]
	at io.jans.keycloak.link.timer.JansKeycloakLinkTimer.isStartCacheRefresh(JansKeycloakLinkTimer.java:211) ~[classes/:?]
	at io.jans.keycloak.link.timer.JansKeycloakLinkTimer.processInt(JansKeycloakLinkTimer.java:187) ~[classes/:?]
	at io.jans.keycloak.link.timer.JansKeycloakLinkTimer$Proxy$_$$_WeldSubclass.processInt(Unknown Source) ~[classes/:?]
	at io.jans.keycloak.link.timer.JansKeycloakLinkTimer.process(JansKeycloakLinkTimer.java:172) ~[classes/:?]
	at io.jans.keycloak.link.timer.JansKeycloakLinkTimer$Proxy$_$$_WeldSubclass.process$$super(Unknown Source) ~[classes/:?]
	at jdk.internal.reflect.GeneratedMethodAccessor53.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.probe.InvocationMonitor$InterceptorAction.proceed(InvocationMonitor.java:199) ~[weld-probe-core-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.probe.InvocationMonitor$InterceptorAction.proceed(InvocationMonitor.java:195) ~[weld-probe-core-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.probe.InvocationMonitor$Action.perform(InvocationMonitor.java:174) ~[weld-probe-core-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.probe.InvocationMonitor.monitor(InvocationMonitor.java:139) ~[weld-probe-core-4.0.3.Final.jar:4.0.3.Final]
	at jdk.internal.reflect.GeneratedMethodAccessor11.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.interceptor.proxy.NonTerminalAroundInvokeInvocationContext.proceedInternal(NonTerminalAroundInvokeInvocationContext.java:66) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
	at io.jans.service.cdi.async.AsynchronousInterceptor$1.get(AsynchronousInterceptor.java:42) ~[jans-core-service-1.1.1-SNAPSHOT.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	at com.sun.crypto.provider.CipherCore.unpad(CipherCore.java:862) ~[?:?]
	at com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:942) ~[?:?]
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:735) ~[?:?]
	at com.sun.crypto.provider.DESedeCipher.engineDoFinal(DESedeCipher.java:295) ~[?:?]
	at javax.crypto.Cipher.doFinal(Cipher.java:2205) ~[?:?]
	at io.jans.util.security.StringEncrypter.decrypt(StringEncrypter.java:208) ~[jans-core-util-1.1.1-SNAPSHOT.jar:?]
	... 74 more
02-04-2024 12:45:03.974 INFO  link.server.service.KeycloakService KeycloakService.java:42- clientSecret is null or not encrypted
02-04-2024 12:45:03.974 INFO  link.server.service.KeycloakService KeycloakService.java:48- password is null or not encrypted
02-04-2024 12:45:03.980 INFO  link.server.service.KeycloakService KeycloakService.java:63- getKeycloakInstance() instance::class org.keycloak.admin.client.Keycloak
02-04-2024 12:45:04.055 ERROR keycloak.link.timer.JansKeycloakLinkTimer JansKeycloakLinkTimer.java:214- not able to connect keycloack server : jakarta.ws.rs.ProcessingException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "features" (class org.keycloak.representations.info.ServerInfoRepresentation), not marked as ignorable (15 known properties: "protocolMapperTypes", "providers", "identityProviders", "themes", "passwordPolicies", "clientInstallations", "memoryInfo", "enums", "socialProviders", "clientImporters", "profileInfo", "componentTypes", "systemInfo", "cryptoInfo", "builtinProtocolMappers"])
 at [Source: (org.jboss.resteasy.specimpl.AbstractBuiltResponse$InputStreamWrapper); line: 1, column: 1271] (through reference chain: org.keycloak.representations.info.ServerInfoRepresentation["features"])
jakarta.ws.rs.client.ResponseProcessingException: jakarta.ws.rs.ProcessingException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "features" (class org.keycloak.representations.info.ServerInfoRepresentation), not marked as ignorable (15 known properties: "protocolMapperTypes", "providers", "identityProviders", "themes", "passwordPolicies", "clientInstallations", "memoryInfo", "enums", "socialProviders", "clientImporters", "profileInfo", "componentTypes", "systemInfo", "cryptoInfo", "builtinProtocolMappers"])
 at [Source: (org.jboss.resteasy.specimpl.AbstractBuiltResponse$InputStreamWrapper); line: 1, column: 1271] (through reference chain: org.keycloak.representations.info.ServerInfoRepresentation["features"])
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:203)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:64)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:154)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at jdk.proxy3/jdk.proxy3.$Proxy99.getInfo(Unknown Source)
	at io.jans.keycloak.link.timer.JansKeycloakLinkTimer.isStartCacheRefresh(JansKeycloakLinkTimer.java:211)
	at io.jans.keycloak.link.timer.JansKeycloakLinkTimer.processInt(JansKeycloakLinkTimer.java:187)
	at io.jans.keycloak.link.timer.JansKeycloakLinkTimer$Proxy$_$$_WeldSubclass.processInt(Unknown Source)
	at io.jans.keycloak.link.timer.JansKeycloakLinkTimer.process(JansKeycloakLinkTimer.java:172)
	at io.jans.keycloak.link.timer.JansKeycloakLinkTimer$Proxy$_$$_WeldSubclass.process$$super(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51)
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78)
	at org.jboss.weld.probe.InvocationMonitor$InterceptorAction.proceed(InvocationMonitor.java:199)
	at org.jboss.weld.probe.InvocationMonitor$InterceptorAction.proceed(InvocationMonitor.java:195)
	at org.jboss.weld.probe.InvocationMonitor$Action.perform(InvocationMonitor.java:174)
	at org.jboss.weld.probe.InvocationMonitor.monitor(InvocationMonitor.java:139)
	at jdk.internal.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
	at org.jboss.weld.interceptor.proxy.NonTerminalAroundInvokeInvocationContext.proceedInternal(NonTerminalAroundInvokeInvocationContext.java:66)
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78)
	at io.jans.service.cdi.async.AsynchronousInterceptor$1.get(AsynchronousInterceptor.java:42)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: jakarta.ws.rs.ProcessingException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "features" (class org.keycloak.representations.info.ServerInfoRepresentation), not marked as ignorable (15 known properties: "protocolMapperTypes", "providers", "identityProviders", "themes", "passwordPolicies", "clientInstallations", "memoryInfo", "enums", "socialProviders", "clientImporters", "profileInfo", "componentTypes", "systemInfo", "cryptoInfo", "builtinProtocolMappers"])
 at [Source: (org.jboss.resteasy.specimpl.AbstractBuiltResponse$InputStreamWrapper); line: 1, column: 1271] (through reference chain: org.keycloak.representations.info.ServerInfoRepresentation["features"])
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:254)
	at org.jboss.resteasy.specimpl.BuiltResponse.readEntity(BuiltResponse.java:90)
	at org.jboss.resteasy.specimpl.AbstractBuiltResponse.readEntity(AbstractBuiltResponse.java:256)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:167)
	... 33 more
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "features" (class org.keycloak.representations.info.ServerInfoRepresentation), not marked as ignorable (15 known properties: "protocolMapperTypes", "providers", "identityProviders", "themes", "passwordPolicies", "clientInstallations", "memoryInfo", "enums", "socialProviders", "clientImporters", "profileInfo", "componentTypes", "systemInfo", "cryptoInfo", "builtinProtocolMappers"])
 at [Source: (org.jboss.resteasy.specimpl.AbstractBuiltResponse$InputStreamWrapper); line: 1, column: 1271] (through reference chain: org.keycloak.representations.info.ServerInfoRepresentation["features"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2036)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:320)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2025)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1175)
	at org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.readFrom(ResteasyJackson2Provider.java:193)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:101)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:80)
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:217)
	... 36 more
02-04-2024 12:45:04.056 INFO  keycloak.link.timer.JansKeycloakLinkTimer JansKeycloakLinkTimer.java:188- Starting conditions aren't reached
02-04-2024 12:45:04.057 INFO  keycloak.link.timer.JansKeycloakLinkTimer JansKeycloakLinkTimer.java:173- Allowing to run new process exclusively
```

**Comment by shekhar16** [comment]
Have you encrypted the client secret key?

**Comment by manojs1978** [comment]
@shekhar16 ,
no, it is not encrypted,  it is what we got from client in KC
