### ISSUE TITLE
fix(document-store): document save throws ERROR: invalid byte sequence for encoding "UTF8": 0x00

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#8204]
Document save functionality throws error in PSQL Database

**Screenshot:**
![image](https://github.com/JanssenProject/jans/assets/43700552/49e136b4-d1b1-4d6c-90d4-753ca63c46e3)

**Error snippet:**
_Caused by: com.querydsl.core.QueryException: Caught PSQLException for insert into "public"."jansDocument" ("creationDate", "description", "displayName", "document", "inum", "jansEnabled", "jansModuleProperty", "objectClass", "dn", "doc_id")
values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        at com.querydsl.sql.DefaultSQLExceptionTranslator.translate(DefaultSQLExceptionTranslator.java:50) ~[querydsl-sql-4.4.0.jar:?]
        at com.querydsl.sql.Configuration.translate(Configuration.java:508) ~[querydsl-sql-4.4.0.jar:?]
        at com.querydsl.sql.dml.AbstractSQLInsertClause.execute(AbstractSQLInsertClause.java:437) ~[querydsl-sql-4.4.0.jar:?]
        at io.jans.orm.sql.operation.impl.SqlOperationServiceImpl.addEntryImpl(SqlOperationServiceImpl.java:209) ~[jans-orm-sql-1.1.1-SNAPSHOT.jar:?]
        at io.jans.orm.sql.operation.impl.SqlOperationServiceImpl.addEntry(SqlOperationServiceImpl.java:177) ~[jans-orm-sql-1.1.1-SNAPSHOT.jar:?]
        at io.jans.orm.sql.impl.SqlEntryManager.persist(SqlEntryManager.java:215) ~[jans-orm-sql-1.1.1-SNAPSHOT.jar:?]
        ... 108 more
Caused by: org.postgresql.util.PSQLException: ERROR: invalid byte sequence for encoding "UTF8": 0x00
  Where: unnamed portal parameter $4_

**Logs:**
[2024_04_02.jetty.log](https://github.com/JanssenProject/jans/files/14837159/2024_04_02.jetty.log)

**Comment by pujavs** [comment]
Two changes made for this;
1. Used `saveBinaryDocumentStream` method instead of `saveDocumentStream`
![image](https://github.com/JanssenProject/jans/assets/43700552/535695d3-c1e8-4226-90b3-745d7d55bcbd)

2. Datatype of `document` field in DB changed from varchar to text
![image](https://github.com/JanssenProject/jans/assets/43700552/523edf38-874b-444e-8e71-dbbeea94ed2e)

**Comment by pujavs** [comment]
Fixed via PR [8215](https://github.com/JanssenProject/jans/pull/8215) and [8211](https://github.com/JanssenProject/jans/pull/8211)
