### ISSUE TITLE
fix(jans-casa): fido script not working

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#8441]
**Describe the bug**
fido script not working

**To Reproduce**
1. install jan 1.1.2.nightly
2. enable fido script
3. login to jans-casa
4. register fido device
5. not able to register 

**Expected behavior**
should able to register fido device

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/3cc9fd88-a63e-4c2a-9cdd-cffdcc1d3323)

**Desktop (please complete the following information):**
  - OS: suse 15 sp5
  - Browser [e.g. chrome, firefox]
  - Version sp 5
  - jans 1.1.2.nightly
  - DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by manojs1978** [comment]
error in fido log
```
03-05 05:50:06.712 INFO  [Thread-108] [io.jans.fido2.service.app.ConfigurationFactory] (ConfigurationFactory.java:276) - Loading configuration from 'sql' DB...
03-05 05:50:06.717 ERROR [Thread-108] [io.jans.fido2.service.app.ConfigurationFactory] (ConfigurationFactory.java:297) - WELD-001334: Unsatisfied dependencies for type AbstractCryptoProvider with qualifiers @Default
org.jboss.weld.exceptions.UnsatisfiedResolutionException: WELD-001334: Unsatisfied dependencies for type AbstractCryptoProvider with qualifiers @Default
        at org.jboss.weld.bean.builtin.InstanceImpl.checkBeanResolved(InstanceImpl.java:241) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
        at org.jboss.weld.bean.builtin.InstanceImpl.get(InstanceImpl.java:113) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
        at io.jans.fido2.service.app.ConfigurationFactory.destroyCryptoProviderInstance(ConfigurationFactory.java:309) ~[classes/:?]
        at io.jans.fido2.service.app.ConfigurationFactory$Proxy$_$$_WeldSubclass.destroyCryptoProviderInstance(Unknown Source) ~[classes/:?]
        at io.jans.fido2.service.app.ConfigurationFactory.createFromDb(ConfigurationFactory.java:288) [classes/:?]
        at io.jans.fido2.service.app.ConfigurationFactory.reloadConfFromLdap(ConfigurationFactory.java:272) [classes/:?]
        at io.jans.fido2.service.app.ConfigurationFactory$Proxy$_$$_WeldSubclass.reloadConfFromLdap(Unknown Source) [classes/:?]
        at io.jans.fido2.service.app.ConfigurationFactory.reloadConfiguration(ConfigurationFactory.java:209) [classes/:?]
        at io.jans.fido2.service.app.ConfigurationFactory.reloadConfigurationTimerEvent(ConfigurationFactory.java:174) [classes/:?]
        at io.jans.fido2.service.app.ConfigurationFactory$Proxy$_$$_WeldSubclass.reloadConfigurationTimerEvent$$super(Unknown Source) [classes/:?]
        at jdk.internal.reflect.GeneratedMethodAccessor46.invoke(Unknown Source) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) [weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
        at io.jans.service.cdi.async.AsynchronousInterceptor$1.get(AsynchronousInterceptor.java:42) [jans-core-service-1.1.2-SNAPSHOT.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
03-05 05:50:06.734 ERROR [Thread-108] [io.jans.fido2.service.app.ConfigurationFactory] (ConfigurationFactory.java:176) - Exception happened while reloading application configuration
io.jans.exception.ConfigurationException: Unable to find configuration in DB...
        at io.jans.fido2.service.app.ConfigurationFactory.createFromDb(ConfigurationFactory.java:300) ~[classes/:?]
        at io.jans.fido2.service.app.ConfigurationFactory.reloadConfFromLdap(ConfigurationFactory.java:272) ~[classes/:?]
        at io.jans.fido2.service.app.ConfigurationFactory$Proxy$_$$_WeldSubclass.reloadConfFromLdap(Unknown Source) ~[classes/:?]
        at io.jans.fido2.service.app.ConfigurationFactory.reloadConfiguration(ConfigurationFactory.java:209) ~[classes/:?]
        at io.jans.fido2.service.app.ConfigurationFactory.reloadConfigurationTimerEvent(ConfigurationFactory.java:174) [classes/:?]
```

**Comment by jgomer2001** [comment]
unable to reproduce
