### ISSUE TITLE
fix(jans-cli-tui): getting error while navigating through tabs in TUI

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#8588]
**Describe the bug**
getting error while navigating through tabs in TUI

**To Reproduce**
1. install jans 1.1.2.nightly
2. launch TUI
3. navingate through tabs in TUI

**Expected behavior**
should not get any error

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/077648f9-3449-4254-a7c1-127606bcf045)

**Desktop (please complete the following information):**
  - OS: ubuntu22
-jans 1.1.2.nightly
-DB opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by manojs1978** [comment]
`
Exception 'Plugin' object has no attribute 'working_container'
Press ENTER to continue...
Press ENTER to continue...

Unhandled exception in event loop:
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/application/application.py", line 1001, in in_term
    async with in_terminal():
  File "/usr/lib/python3.10/contextlib.py", line 206, in __aexit__
    await anext(self.gen)
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/application/run_in_terminal.py", line 115, in in_terminal
    app._redraw()
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/application/application.py", line 557, in _redraw
    self.context.copy().run(run_in_context)
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/application/application.py", line 540, in run_in_context
    self.renderer.render(self, self.layout)
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/renderer.py", line 675, in render
    layout.container.write_to_screen(
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 810, in write_to_screen
    self.content.write_to_screen(
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 400, in write_to_screen
    c.write_to_screen(
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 810, in write_to_screen
    self.content.write_to_screen(
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 384, in write_to_screen
    sizes = self._divide_heights(write_position)
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 438, in _divide_heights
    dimensions = [c.preferred_height(width, height) for c in self._all_children]
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 438, in <listcomp>
    dimensions = [c.preferred_height(width, height) for c in self._all_children]
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 572, in preferred_height
    sizes = self._divide_widths(width)
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 633, in _divide_widths
    dimensions = [c.preferred_width(width) for c in children]
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 633, in <listcomp>
    dimensions = [c.preferred_width(width) for c in children]
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 2690, in preferred_width
    return self._get_container().preferred_width(max_available_width)
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 2690, in preferred_width
    return self._get_container().preferred_width(max_available_width)
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 2690, in preferred_width
    return self._get_container().preferred_width(max_available_width)
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 2683, in _get_container
    obj = self.get_container()
  File "/opt/jans/jans-cli/plugins/120_lock/main.py", line 36, in <lambda>
    self.main_container = DynamicContainer(lambda: self.working_container)

Exception 'Plugin' object has no attribute 'working_container'

Unhandled exception in event loop:
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/application/application.py", line 1001, in in_term
    async with in_terminal():
  File "/usr/lib/python3.10/contextlib.py", line 206, in __aexit__
    await anext(self.gen)
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/application/run_in_terminal.py", line 115, in in_terminal
    app._redraw()
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/application/application.py", line 557, in _redraw
    self.context.copy().run(run_in_context)
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/application/application.py", line 540, in run_in_context
    self.renderer.render(self, self.layout)
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/renderer.py", line 675, in render
    layout.container.write_to_screen(
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 810, in write_to_screen
    self.content.write_to_screen(
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 400, in write_to_screen
    c.write_to_screen(
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 810, in write_to_screen
    self.content.write_to_screen(
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 384, in write_to_screen
    sizes = self._divide_heights(write_position)
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 438, in _divide_heights
    dimensions = [c.preferred_height(width, height) for c in self._all_children]
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 438, in <listcomp>
    dimensions = [c.preferred_height(width, height) for c in self._all_children]
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 572, in preferred_height
    sizes = self._divide_widths(width)
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 633, in _divide_widths
    dimensions = [c.preferred_width(width) for c in children]
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 633, in <listcomp>
    dimensions = [c.preferred_width(width) for c in children]
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 2690, in preferred_width
    return self._get_container().preferred_width(max_available_width)
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 2690, in preferred_width
    return self._get_container().preferred_width(max_available_width)
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 2690, in preferred_width
    return self._get_container().preferred_width(max_available_width)
  File "/opt/jans/jans-cli/cli/pylib/prompt_toolkit/layout/containers.py", line 2683, in _get_container
    obj = self.get_container()
  File "/opt/jans/jans-cli/plugins/120_lock/main.py", line 36, in <lambda>
    self.main_container = DynamicContainer(lambda: self.working_container)

Exception 'Plugin' object has no attribute 'working_container'
`

**Comment by MohitMaliFtechiz** [comment]
``` 27-05 06:02:45.649 ERROR [qtp1301664418-20] jans.configapi.filters.AuthorizationFilter AuthorizationFilter.java:94- ======AUTHORIZATION  FAILED ===========================================                                                                                                                             org.jboss.resteasy.client.exception.ResteasyNotAuthorizedException: HTTP 401 Unauthorized                                                                           at org.jboss.resteasy.client.exception.WebApplicationExceptionWrapper.wrap(WebApplicationExceptionWrapper.java:74) ~[resteasy-client-api-6.0.3.Final.jar:6.0.3.Final]
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:266) ~[resteasy-client-6.0.3.Final.jar:6.0.3.Final] ```
i am getting unauthorized error on config api

**Comment by devrimyatar** [comment]
I were not be able to replicate this issue when I install with `install.py`. @manojs1978 Please re-test after new deb rebuild and re-open if necassary.
