### ISSUE TITLE
fix: using setup.properties for installing with different persistences

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#8985]
### COUCHBASE
If the following is passed 
```
hostname=demoexample.jans.io
admin_password=1t5Fin3#security
orgName=Janssen
admin_email=support@jans.io
city=Austin
state=TX
countryCode=US
ldapPass=1t5Fin3#security
installLdap=False
install_config_api=True
install_scim_server=True
installFido2=True
install_casa=True
install_jans_keycloak_link=True
install_jans_link=True
install_jans_lock=True
install_jans_saml=True
install_opa=True
test_client_id=9876baac-de39-4c23-8a78-674b59df8c09
test_client_pw=1t5Fin3#security
test_client_trusted=True
loadTestData=True
cb_install=2
cb_password=password
couchbase_hostname=couchbase
couchebaseClusterAdmin=Administrator
```
It produces 

```
hostname                                      demoexample.jans.io
orgName                                                   Janssen
os                                                         ubuntu
city                                                       Austin
state                                                          TX
countryCode                                                    US
Applications max ram (MB)                                   13260
Backends                                      couchbase[R], pgsql
Java Type                                                     jre
Install Apache 2 web server                                  True
Install Auth Server                                          True
Install Jans Config API                                      True
Install Fido2 Server                                         True
Install Scim Server                                          True
Install Jans Link Server                                     True
Install Jans KC Link Server                                  True
Install Jans Casa                                            True
Install Jans Lock                                            True
Install Jans KC                                              True
Load Test Data                                               True
```

#### OPENDJ 

```
hostname=demoexample.jans.io
admin_password=1t5Fin3#security
orgName=Janssen
admin_email=support@jans.io
city=Austin
state=TX
countryCode=US
ldapPass=1t5Fin3#security
installLdap=True
install_config_api=True
install_scim_server=True
installFido2=True
install_casa=True
install_jans_keycloak_link=True
install_jans_link=True
install_jans_lock=True
install_jans_saml=True
install_opa=True
test_client_id=9876baac-de39-4c23-8a78-674b59df8c09
test_client_pw=1t5Fin3#security
test_client_trusted=True
loadTestData=True
```

produces 

```
hostname                                      demoexample.jans.io
orgName                                                   Janssen
os                                                         ubuntu
city                                                       Austin
state                                                          TX
countryCode                                                    US
Applications max ram (MB)                                   10608
OpenDJ max ram (MB)                                          2652
Backends                                            opendj, pgsql
Java Type                                                     jre
Install Apache 2 web server                                  True
Install Auth Server                                          True
Install Jans Config API                                      True
Install Fido2 Server                                         True
Install Scim Server                                          True
Install Jans Link Server                                     True
Install Jans KC Link Server                                  True
Install Jans Casa                                            True
Install Jans Lock                                            True
Install Jans KC                                              True
Load Test Data                                               True

Process jans: Calculating application memory
Process jre: Installing Jre
Process jre: Downloading amazon-corretto-17-x64-linux-jdk.tar.gz
Process jetty: Installing Jetty
Process jetty: Downloading jetty-home-11.0.15.tar.gz
Process jython: Installing Jython
Process jython: Downloading jython-installer-2.7.3.jar
Process jans: Generating smtp keys
Process opendj: Installing OpenDJ
Process opendj: Downloading opendj-server-legacy-4.5.1.zip
Process opendj: Extracting OpenDJ
Process opendj: Installing OpenDJ
Process opendj: Setting up OpenDJ service
Process opendj: Preparing OpenDJ schema
FATAL: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: http://sqlalche.me/e/13/e3q8)
Process opendj: Creating OpenDJ backends
Process opendj: Configuring OpenDJ
FATAL: True
Traceback (most recent call last):
  File "/opt/jans/jans-setup/setup.py", line 415, in do_installation
    openDjInstaller.start_installation()
  File "/opt/jans/jans-setup/setup_app/installers/base.py", line 38, in start_installation
    self.install()
  File "/opt/jans/jans-setup/setup_app/installers/opendj.py", line 67, in install
    self.configure_opendj()
  File "/opt/jans/jans-setup/setup_app/installers/opendj.py", line 239, in configure_opendj
    self.dbUtils.ldap_conn.modify(
AttributeError: 'DBUtils' object has no attribute 'ldap_conn'
```

### SPANNER

```
hostname                                      demoexample.jans.io
orgName                                                   Janssen
os                                                         ubuntu
city                                                       Austin
state                                                          TX
countryCode                                                    US
Applications max ram (MB)                                   13260
Backends                                                  spanner
Java Type                                                     jre
Install Apache 2 web server                                  True
Install Auth Server                                          True
Install Jans Config API                                      True
Install Fido2 Server                                         True
Install Scim Server                                          True
Install Jans Link Server                                     True
Install Jans KC Link Server                                  True
Install Jans Casa                                            True
Install Jans Lock                                            True
Install Jans KC                                              True
Load Test Data                                               True
Process jans: Calculating application memory
Process jre: Installing Jre
Process jre: Downloading amazon-corretto-17-x64-linux-jdk.tar.gz
Process jetty: Installing Jetty
Process jetty: Downloading jetty-home-11.0.15.tar.gz
Process jython: Installing Jython
Process jython: Downloading jython-installer-2.7.3.jar
Process jans: Generating smtp keys
Process rdbm-server: Installing Rdbm-Server
Process rdbm-server: Downloading jans-orm-spanner-libs-distribution.zip
FATAL: True
Traceback (most recent call last):
  File "/opt/jans/jans-setup/setup.py", line 421, in do_installation
    rdbmInstaller.start_installation()
  File "/opt/jans/jans-setup/setup_app/installers/base.py", line 38, in start_installation
    self.install()
  File "/opt/jans/jans-setup/setup_app/installers/rdbm.py", line 49, in install
    self.local_install()
  File "/opt/jans/jans-setup/setup_app/installers/rdbm.py", line 190, in local_install
    self.dbUtils.bind(force=True)
  File "/opt/jans/jans-setup/setup_app/utils/db_utils.py", line 70, in bind
    self.spanner_client = SpannerClient(
  File "/opt/jans/jans-setup/setup_app/utils/spanner_rest_client.py", line 38, in __init__
    self.get_session()
  File "/opt/jans/jans-setup/setup_app/utils/spanner_rest_client.py", line 107, in get_session
    self.sessioned_url = os.path.join(self.spanner_base_url, result['name'])
KeyError: 'name'
Downloading https://github.com/JanssenProject/jans/archive/refs/heads/main.zip as /opt/dist/jans/jans.zip
Extracting jans-setup package
Launching Janssen Setup
Executing /usr/bin/python3 /opt/jans/jans-setup/setup.py -f setup.properties -n

```

Produces 

```
hostname=demoexample.jans.io
admin_password=1t5Fin3#security
orgName=Janssen
admin_email=support@jans.io
city=Austin
state=TX
countryCode=US
ldapPass=1t5Fin3#security
installLdap=False
install_config_api=True
install_scim_server=True
installFido2=True
install_casa=True
install_jans_keycloak_link=True
install_jans_link=True
install_jans_lock=True
install_jans_saml=True
install_opa=True
test_client_id=9876baac-de39-4c23-8a78-674b59df8c09
test_client_pw=1t5Fin3#security
test_client_trusted=True
loadTestData=True
rdbm_type=spanner
rdbm_install_type=1
spanner_emulator_host=localhost
```

**Comment by devrimyatar** [comment]
@moabu setup can't install spanner emulator. It is not possible to automate spanner emulator installetion. So you should install spanner emulator manually and add these to your setup.properties file:

rdbm_type=spanner
rdbm_install_type=2
spanner_emulator_host=myhost
spanner_project=jans-project
spanner_instance=jans-instance
spanner_database=jansdb
