### ISSUE TITLE
u2f script crashes upon authentication

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#905]
Error in script log

```
2022-02-25 14:40:26,354 INFO  [qtp2024453272-17] 5dd113f5-41f7-43f7-bde1-4ed9ccf4201c [io.jans.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - U2F. Authenticate for step 2
2022-02-25 14:40:26,355 INFO  [qtp2024453272-17] 5dd113f5-41f7-43f7-bde1-4ed9ccf4201c [io.jans.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - U2F. Prepare for step 2. Call FIDO U2F in order to finish authentication workflow
2022-02-25 14:40:26,426 ERROR [qtp2024453272-17] 5dd113f5-41f7-43f7-bde1-4ed9ccf4201c [jans.as.server.service.external.ExternalAuthenticationService] (ExternalAuthenticationService.java:216) - AttributeError: type object 'io.jans.as.model.config.Constants' has no attribute 'RESULT_SUCCESS'
org.python.core.PyException: AttributeError: type object 'io.jans.as.model.config.Constants' has no attribute 'RESULT_SUCCESS'
	at org.python.core.Py.AttributeError(Py.java:178) ~[jython-standalone-2.7.3.jar:2.7.3-SNAPSHOT]
	at org.python.core.PyType.noAttributeError(PyType.java:2592) ~[jython-standalone-2.7.3.jar:2.7.3-SNAPSHOT]
	at org.python.core.PyObject.__getattr__(PyObject.java:959) ~[jython-standalone-2.7.3.jar:2.7.3-SNAPSHOT]
	at casa-external_u2f$py.authenticate$9(/opt/jans/python/libs/casa-external_u2f.py:136) ~[?:?]
	at casa-external_u2f$py.call_function(/opt/jans/python/libs/casa-external_u2f.py) ~[?:?]
	at org.python.core.PyTableCode.call(PyTableCode.java:173) ~[jython-standalone-2.7.3.jar:2.7.3-SNAPSHOT]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:187) ~[jython-standalone-2.7.3.jar:2.7.3-SNAPSHOT]
	at org.python.core.PyFunction.__call__(PyFunction.java:449) ~[jython-standalone-2.7.3.jar:2.7.3-SNAPSHOT]
	at org.python.core.PyMethod.__call__(PyMethod.java:171) ~[jython-standalone-2.7.3.jar:2.7.3-SNAPSHOT]
	at org.python.pycode._pyx9.authenticate$9(casa.py:193) ~[?:?]
	at org.python.pycode._pyx9.call_function(casa.py) ~[?:?]
	at org.python.core.PyTableCode.call(PyTableCode.java:173) ~[jython-standalone-2.7.3.jar:2.7.3-SNAPSHOT]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:306) ~[jython-standalone-2.7.3.jar:2.7.3-SNAPSHOT]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:197) ~[jython-standalone-2.7.3.jar:2.7.3-SNAPSHOT]
	at org.python.core.PyFunction.__call__(PyFunction.java:485) ~[jython-standalone-2.7.3.jar:2.7.3-SNAPSHOT]
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237) ~[jython-standalone-2.7.3.jar:2.7.3-SNAPSHOT]
	at org.python.core.PyMethod.__call__(PyMethod.java:228) ~[jython-standalone-2.7.3.jar:2.7.3-SNAPSHOT]
	at org.python.core.PyMethod.__call__(PyMethod.java:218) ~[jython-standalone-2.7.3.jar:2.7.3-SNAPSHOT]
	at org.python.core.PyMethod.__call__(PyMethod.java:213) ~[jython-standalone-2.7.3.jar:2.7.3-SNAPSHOT]
	at org.python.core.PyObject._jcallexc(PyObject.java:3565) ~[jython-standalone-2.7.3.jar:2.7.3-SNAPSHOT]
	at org.python.core.PyObject._jcall(PyObject.java:3598) ~[jython-standalone-2.7.3.jar:2.7.3-SNAPSHOT]
	at org.python.proxies.__main__$PersonAuthentication$13.authenticate(Unknown Source) ~[?:?]
	at io.jans.as.server.service.external.ExternalAuthenticationService.executeExternalAuthenticate(ExternalAuthenticationService.java:214) ~[classes/:?]
	at io.jans.as.server.service.external.ExternalAuthenticationService$Proxy$_$$_WeldClientProxy.executeExternalAuthenticate(Unknown Source) ~[classes/:?]
	at io.jans.as.server.auth.Authenticator.userAuthenticationInteractive(Authenticator.java:343) ~[classes/:?]
	at io.jans.as.server.auth.Authenticator.authenticateImpl(Authenticator.java:225) ~[classes/:?]
	at io.jans.as.server.auth.Authenticator.authenticateWithOutcome(Authenticator.java:164) ~[classes/:?]
```

**Comment by maduvena** [comment]
#3088 - will be fixed when this PR is merged.
