### ISSUE TITLE
fix(jans-cli): getting error  when accessing SSA information using jans-cli

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#9597]
**Describe the bug**
 getting error  when accessing SSA information using jans-cli

**To Reproduce**
1. install jans 
2. complete device auth
3. run jans-cli command to get SSA details `/opt/jans/jans-cli/cli/config_cli.py -auth --info Ssa`

**Expected behavior**
should not get error

**Screenshots**
![image](https://github.com/user-attachments/assets/370b3ee5-739f-47cd-be92-83fd093e3baf)

**Desktop (please complete the following information):**
  - OS: ubuntu22
- jans 1.1.6.nightly
- DB opendj
- 
**Smartphone (please complete the following information):**

**Additional context**
```
root@manojs1978-funny-coral:~# /opt/jans/jans-cli/cli/config_cli.py -auth --info Ssa
Operation ID: post-register-ssa
  Description: # Create SSA for the organization with `expiration` (optional).
----

**Security: Bearer Auth**

Provide your bearer token in the Authorization header when making requests to protected resources.

Example: `Authorization: Bearer {{your-access-token}}`

**Security: OAuth 2.0**

Scopes:
- `https://jans.io/auth/ssa.admin` - **SSA Admin**, You can create `SSA`.
  Parameters:
    org_id*: The `org_id` is used for organization identification.
    description: Description SSA.
    expiration: Expiration date. If this field is not sent, it will take days to expire, according to how it has been configured.
    software_id*: The `software_id` is used for software identification.
    software_roles*: List of string values, fixed value ["password", "notify"].
    grant_types*: Fixed value ["client_credentials"].
    one_time_use*: Defined whether the SSA will be used only once or can be used multiple times.
    rotate_ssa*: TODO - Will be used to rotate expiration of the SSA, currently is only saved as part of the SSA.
    lifetime: SSA lifetime in seconds.
Operation ID: get-ssa
  Description: # Get all SSA list based on `jti` or `org_id`.
----

**Security: Bearer Auth**

Provide your bearer token in the Authorization header when making requests to protected resources.

Example: `Authorization: Bearer {{your-access-token}}`

**Security: OAuth 2.0**

Scopes:
- `https://jans.io/auth/ssa.admin` - **SSA Adm
.in**, Retrieves all `SSA`
- `https://jans.io/auth/ssa.portal` - **SSA Portal**, Retrieves all `SSA`
- `https://jans.io/auth/ssa.developer` - **SSA Developer**, Retrieves the `SSA` created by the same client
  Parameters:
  jti: Unique Identifier [string]
  org_id: Organization ID [string]
Operation ID: delete-ssa
  Description: # Revokes existing active SSA based on `jti` or `org_id`
----

- `jti` - for delete only one SSA, the specified by `jti` 
- `org_id` - for delete all SSA of the specified organization.

**Security: Bearer Auth**

Provide your bearer token in the Authorization header when making requests to protected resources.

Example: `Authorization: Bearer {{your-access-token}}`

**Security: OAuth 2.0**

Scopes:
- `https://jans.io/auth/ssa.admin` - **SSA Admin**, You can revoke `SSA`.
  Parameters:
  jti: A unique identifier for the token, which can be used to prevent reuse of the token. [string]
  org_id: Delete all SSAs of the specified organization. [string]
An Unhandled error raised: 'operationId'
Error is logged to /root/cli_error.log
```

error in ci_error.log
```
Traceback (most recent call last):
  File "/opt/jans/jans-cli/cli/config_cli.py", line 1622, in main
    cli_object.help_for(args.info)
  File "/opt/jans/jans-cli/cli/config_cli.py", line 1063, in help_for
    print('Operation ID:', path['operationId'])
  File "/usr/lib/python3/dist-packages/ruamel/yaml/comments.py", line 926, in __getitem__
    return ordereddict.__getitem__(self, key)
KeyError: 'operationId'
Traceback (most recent call last):
  File "/opt/jans/jans-cli/cli/config_cli.py", line 1622, in main
    cli_object.help_for(args.info)
  File "/opt/jans/jans-cli/cli/config_cli.py", line 1063, in help_for
    print('Operation ID:', path['operationId'])
  File "/usr/lib/python3/dist-packages/ruamel/yaml/comments.py", line 926, in __getitem__
    return ordereddict.__getitem__(self, key)
KeyError: 'operationId'
```

**Comment by yuriyz** [comment]
@devrimyatar fixed in https://github.com/JanssenProject/jans/pull/9601
