### ISSUE TITLE
fix(jans-setup): getting error "KC did not start in 150 second" while installing jans 

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#9760]
**Describe the bug**
getting error "KC did not start in 150 second" while installing jans with mysql

**To Reproduce**
1. install jans with mysql
2. See error

**Expected behavior**
should not get any error

**Screenshots**
![image](https://github.com/user-attachments/assets/e70efe95-b0ef-4d13-bf7b-cf130cee91f4)

**Desktop (please complete the following information):**
  - OS: uubntu22
-jans 1.1.6.nightly
DB mysql
**Smartphone (please complete the following information):**

**Additional context**
```
Install Jans Config API? [Yes] : 
Install Scim Server? [Yes] : 
Install Fido2 Server? [Yes] : 
Install Jans LDAP Link Server? [No] : yes
Install Jans KC Link Server? [No] : yes
Install Jans Casa? [No] : yes
Install Jans Lock? [No] : yes
  Install Jans Lock as Server? [No] : yes
  Install OPA? [No] : yes
Install Jans KC? [No] : yes

hostname                      manojs1978-elegant-catfish.gluu.info
orgName                                                   ddfsdfd
os                                                         ubuntu
city                                                        sdfsd
state                                                          dd
countryCode                                                    dd
Applications max ram (MB)                                    6630
Backends                                                    mysql
Java Type                                                     jre
Install Apache 2 web server                                  True
Install Auth Server                                          True
Install Jans Config API                                      True
Install Fido2 Server                                         True
Install Scim Server                                          True
Install Jans LDAP Link Server                                True
Install Jans KC Link Server                                  True
Install Jans Casa                                            True
Install Jans Lock                                            True
Install Jans KC                                              True

Proceed with these values [Y|n] y
The following packages are required for Janssen Server
mysql-server
Do you want to install these now? [Y/n] y
Installing packages mysql-server
FATAL: True
Traceback (most recent call last):
  File "/opt/jans/jans-setup/flex/flex-linux-setup/flex_setup.py", line 187, in <module>
    from jans_setup import jans_setup
ImportError: cannot import name 'jans_setup' from 'jans_setup' (/opt/jans/jans-setup/jans_setup.py)

FATAL: True
Traceback (most recent call last):
  File "/opt/jans/jans-setup/flex/flex-linux-setup/flex_setup.py", line 187, in <module>
    from jans_setup import jans_setup
ImportError: cannot import name 'jans_setup' from 'jans_setup' (/opt/jans/jans-setup/jans_setup.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/jans/jans-setup/jans_setup.py", line 453, in do_installation
    jans_saml_installer.start_installation()
  File "/opt/jans/jans-setup/setup_app/installers/base.py", line 48, in start_installation
    self.service_post_setup()
  File "/opt/jans/jans-setup/setup_app/installers/jans_saml.py", line 174, in service_post_setup
    self.config_api_idp_plugin_config()
  File "/opt/jans/jans-setup/setup_app/installers/jans_saml.py", line 221, in config_api_idp_plugin_config
    self.logIt("KC did not start in 150 seconds. Giving up configuration", errorLog=True, fatal=True)
  File "/opt/jans/jans-setup/setup_app/utils/setup_utils.py", line 53, in logIt
    base.logIt(*args, **kwargs)
  File "/opt/jans/jans-setup/setup_app/utils/base.py", line 229, in logIt
    sys.exit(1)
SystemExit: 1

```

**Comment by devrimyatar** [comment]
@uprightech KC is not starting. See the log:

```
2024-10-16 14:09:28,567 WARN  [org.keycloak.quarkus.runtime.cli.Picocli] (main) The following run time options were found, but will be ignored during build time: kc.spi-hostname-v2-hostname

2024-10-16 14:09:29,937 INFO  [io.jans.kc.spi.custom.impl.DefaultJansThinBridgeProviderFactory] (main) Establishing connection with janssen database
2024-10-16 14:09:30,248 INFO  [org.reflections.Reflections] (main) Reflections took 214 ms to scan 12 urls, producing 45 keys and 155 values
2024-10-16 14:09:30,291 INFO  [io.jans.orm.service.PersistanceFactoryService] (main) Found '5' PersistenceEntryManagerFactory
2024-10-16 14:09:30,291 INFO  [io.jans.orm.service.PersistanceFactoryService] (main) Found PersistenceEntryManagerFactory 'class io.jans.orm.ldap.impl.LdapEntryManagerFactory'
2024-10-16 14:09:30,296 INFO  [io.jans.orm.service.PersistanceFactoryService] (main) Found PersistenceEntryManagerFactory 'class io.jans.orm.hybrid.impl.HybridEntryManagerFactory'
2024-10-16 14:09:30,297 INFO  [io.jans.orm.service.PersistanceFactoryService] (main) Found PersistenceEntryManagerFactory 'class io.jans.orm.sql.impl.SqlEntryManagerFactory'
2024-10-16 14:09:30,297 INFO  [io.jans.orm.service.PersistanceFactoryService] (main) Found PersistenceEntryManagerFactory 'class io.jans.orm.cloud.spanner.impl.SpannerEntryManagerFactory'
2024-10-16 14:09:30,298 INFO  [io.jans.orm.service.PersistanceFactoryService] (main) Found PersistenceEntryManagerFactory 'class io.jans.orm.couchbase.impl.CouchbaseEntryManagerFactory'
2024-10-16 14:09:30,347 INFO  [io.jans.orm.sql.operation.impl.SqlConnectionProvider] (main) Attempting to create connection pool: '1'
2024-10-16 14:09:30,531 WARN  [org.apache.commons.dbcp2.PoolingDataSource] (main) PoolableConnectionFactory not linked to pool. Calling setPool() to fix the configuration.
2024-10-16 14:09:30,667 INFO  [io.opentelemetry.api.GlobalOpenTelemetry] (main) AutoConfiguredOpenTelemetrySdk found on classpath but automatic configuration is disabled. To enable, run your JVM with -Dotel.java.global-autoconfigure.enabled=true
2024-10-16 14:09:31,231 INFO  [io.jans.orm.sql.operation.impl.SqlConnectionProvider] (main) Created connection pool
2024-10-16 14:09:31,239 INFO  [io.jans.orm.sql.operation.impl.SqlConnectionProvider] (main) Detecting engine types...
2024-10-16 14:09:31,355 INFO  [io.jans.orm.sql.operation.impl.SqlConnectionProvider] (main) Scanning DB metadata...
2024-10-16 14:09:32,325 INFO  [io.jans.orm.sql.operation.impl.SqlConnectionProvider] (main) Metadata scan finisehd in 1086 milliseconds
2024-10-16 14:09:32,760 INFO  [io.jans.orm.sql.impl.SqlEntryManagerFactory] (main) Created SqlEntryManager: io.jans.orm.sql.operation.impl.SqlOperationServiceImpl@5a47730c
2024-10-16 14:09:32,760 INFO  [io.jans.kc.spi.custom.impl.DefaultJansThinBridgeProviderFactory] (main) Connection established to janssen database
2024-10-16 14:09:32,783 INFO  [org.keycloak.url.HostnameV2ProviderFactory] (main) If hostanme is specified, hostname-strict is effectively ignored
2024-10-16 14:09:37,019 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Starting Infinispan embedded cache manager
2024-10-16 14:09:37,618 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Persistent user sessions enabled and no memory limit found in configuration. Setting max entries for sessions to 10000 entries.
2024-10-16 14:09:37,619 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Persistent user sessions enabled and no memory limit found in configuration. Setting max entries for clientSessions to 10000 entries.
2024-10-16 14:09:37,619 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Persistent user sessions enabled and no memory limit found in configuration. Setting max entries for offlineSessions to 10000 entries.
2024-10-16 14:09:37,620 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Persistent user sessions enabled and no memory limit found in configuration. Setting max entries for offlineClientSessions to 10000 entries.
2024-10-16 14:09:38,094 INFO  [io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder] (main) Error encountered during autoconfiguration. Closing partially configured components.
2024-10-16 14:09:38,116 INFO  [com.arjuna.ats.jbossatx] (main) ARJUNA032014: Stopping transaction recovery manager
```

**Comment by uprightech** [comment]
We'll have to downgrade KC to 25.0.6

**Comment by devrimyatar** [comment]
Downgraded to 25.0.6
https://github.com/JanssenProject/jans/commit/6220e9c6b74a4736ea6abfbc9aaa44f1e50b8290
