### ISSUE TITLE
bug: build failed to to reference of removed tests

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#996]
**Describe the bug**
We got build failure due to references of removed tests in testng xml.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project jans-auth-server: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: There was an error in the forked process
[ERROR] org.testng.TestNGException: 
[ERROR] 
[ERROR] Cannot find class in classpath: io.jans.as.server.service.fido.u2f.RawAuthenticationServiceTest
[ERROR] 	at org.testng.xml.XmlClass.loadClass(XmlClass.java:77)
[ERROR] 	at org.testng.xml.XmlClass.init(XmlClass.java:69)
```

**Comment by yuriyz** [comment]
Fixed
